### ISSUE TITLE
有选项能不把ü转成v吗？如绿色lv se

### ISSUE THREAD

**Issue by jeremy886** [mozillazg/python-pinyin#10]
虽然v可以在python中轻易转换，不过还是想问一下，是不是有办法不用lv se(绿色)，而用lü se，我是中文教师，如果用lv会和一般教材产生不统一的问题。

这个工具是我最爱用的python工具之一，非常感谢!

**Comment by mozillazg** [comment]
@jeremy886 很高兴这个模块对你有用。
设置 `style=pypinyin.TONE` 就可以了。
各种风格见: http://pypinyin.readthedocs.org/en/latest/#api

```python
>>> pypinyin.pinyin(u'绿色', style=pypinyin.TONE)
[[u'l\u01dc'], [u's\xe8']]
>>> pypinyin.lazy_pinyin(u'绿色', style=pypinyin.TONE)
[u'l\u01dc', u's\xe8']
>>> print ' '.join(pypinyin.lazy_pinyin(u'绿色', style=pypinyin.TONE))
lǜ sè
```
