### ISSUE TITLE
「阿」字在词组中没有被注音

### ISSUE THREAD

**Issue by imdreamrunner** [mozillazg/python-pinyin#106]
pypinyin 0.26.0

```
>>> from pypinyin import pinyin, lazy_pinyin, Style
>>> word = '穆彰阿'
>>> pinyin(word,  heteronym=True)
[['mù'], ['zhāng']]  # 这里漏掉了阿
>>> pinyin(word,  heteronym=False)
[['mù'], ['zhāng']]  # 这里漏掉了阿
>>> word = '穆彰'
>>> pinyin(word,  heteronym=False)
[['mù'], ['zhāng']]
>>> pinyin(word,  heteronym=True)
[['mù'], ['zhāng']]
>>> word = '彰阿'  # 这里没有漏掉阿
>>> pinyin(word,  heteronym=True)
[['zhāng'], ['ā', 'ē', 'ě', 'ǎ', 'à', 'a']]
```

**Comment by mozillazg** [comment]
@imdreamrunner 感谢反馈！我会尽快抽空看一下的。

**Comment by mozillazg** [comment]
@imdreamrunner 请教，`穆彰阿` 的 `阿` 读 `ā` 还是 `ē` 来着？

**Comment by imdreamrunner** [comment]
@mozillazg 您好，感谢您这么快的修正。其实我也不确定他的正确读音，感觉一般读 `ā`

**Comment by imdreamrunner** [comment]
@mozillazg 很好奇为什么之前的 phrase-data 会漏掉好些阿字呢？

**Comment by mozillazg** [comment]
@imdreamrunner 0.26.1 已修复。可能是当时使用的原始拼音数据就有问题。

**Comment by zgdlime** [comment]
@imdreamrunner
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！
