### ISSUE TITLE
能否使生成的拼音声母和韵母以空格分开？

### ISSUE THREAD

**Issue by zuoxiang95** [mozillazg/python-pinyin#108]
## 版本信息

* 操作系统：
* Python 版本：2.7
* pypinyin 版本：0.27.0

P.S. 可以通过 `python -V` 获取 Python 版本。  
P.S. 可以通过 `pypinyin -V` 或者 `pip freeze |grep pypinyin` 或 `pypinyin.__version__` 获取 pypinyin 版本信息。

## 问题描述
我想生成的拼音的格式如下所示：
好： h ao3
中间使以空格将声母和韵母分开，多谢！

**Comment by mozillazg** [comment]
@zuoxiang95 至少两种方法：

* 对函数输出结果进行加工：比如先通过 https://github.com/mozillazg/python-pinyin/blob/master/pypinyin/style/_utils.py#L12 的 `get_initials` 函数获取结果中的声母，剩下的可以作为韵母，然后再把声母和韵母通过空格拼接起来。
* 覆盖掉默认的拼音风格转换函数：所有的拼音风格转换函数都在 https://github.com/mozillazg/python-pinyin/tree/master/pypinyin/style 目录下

**Comment by zuoxiang95** [comment]
好的，我用get_initials已经可以了~多谢~

**Comment by zgdlime** [comment]
@zuoxiang95
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！
