### ISSUE TITLE
“嗯”字的发音不对

### ISSUE THREAD

**Issue by zuoxiang95** [mozillazg/python-pinyin#109]
## 版本信息

* 操作系统：
* Python 版本：
* pypinyin 版本：

P.S. 可以通过 `python -V` 获取 Python 版本。  
P.S. 可以通过 `pypinyin -V` 或者 `pip freeze |grep pypinyin` 或 `pypinyin.__version__` 获取 pypinyin 版本信息。

## 问题描述
@mozillazg 
对“嗯”字用pypinyin转化的时候，输出的是n2，不应该是en3么？

**Comment by mozillazg** [comment]
@zuoxiang95 `嗯` 其实就是 `n2` 没有 `en3` 这个读音，`en` 这个是拼音输入法的习惯。

在《现代汉语词典》中，`嗯` 的读音如下:

<img width="509" alt="image" src="https://user-images.githubusercontent.com/485054/32608131-51a46762-c596-11e7-809c-601654cc6c7d.png">

**Comment by zuoxiang95** [comment]
嗯嗯，多谢了，涨知识了^ ^

**Comment by Momingcoder** [comment]
类似的还有 '呣'，'ḿ'。
我在做输入法引擎的时候发现的，非常特殊的几个拼音，不知道还有没有其他的。

**Comment by mozillazg** [comment]
@Momingcoder 目前发现有 `ḿ`、`ń`、`ň`、`ǹ` 这几个鼻音，汉字的话有好几个，可以在 https://github.com/mozillazg/pinyin-data/blob/master/pinyin.txt 中搜索这几个鼻音字符。
