### ISSUE TITLE
maybe a bug - 苹果 =>  pin guo

### ISSUE THREAD

**Issue by jeremy886** [mozillazg/python-pinyin#11]
>>> import pypinyin
>>> zi = '苹果'
>>> py = pypinyin.slug(zi, style=pypinyin.NORMAL, separator=' ')
Building Trie..., from /usr/local/lib/python3.4/site-packages/jieba/dict.txt
loading model from cache /var/folders/k9/47fd1ycj2rg19gn7d2g5g16c0000gn/T/jieba.cache
loading model cost 2.451965808868408 seconds.
Trie has been built succesfully.
>>> print(py)
pin guo

What I was looking for is "ping guo".

Do we use a conversion table in python-pinyin? I probably should search for it before asking. If yes, I'm interested in this table.

**Comment by mozillazg** [comment]
@jeremy886 `苹果` [有的网站](http://www.zdic.net/c/9/151/335612.htm)是 `pín guǒ`, 有的是 `píng guǒ`，手边没有《现代汉语词典》不知道哪个是对的。
字的读音在这里：https://github.com/mozillazg/python-pinyin/blob/master/pypinyin/pinyin_dict.py
词的读音在这里：https://github.com/mozillazg/python-pinyin/blob/master/pypinyin/phrases_dict.py

**Comment by jeremy886** [comment]
我在墨尔本中学教汉语，手上的书和字典的苹果都是píng guǒ。需要我帮忙修改吗？

**Comment by mozillazg** [comment]
@jeremy886 谢谢！我来改吧。
```python
In [3]: pypinyin.lazy_pinyin(u'苹果', pypinyin.TONE2)
Out[3]: [u'pi2ng', u'guo3']

In [4]: pypinyin.lazy_pinyin(u'金苹果', pypinyin.TONE2)
Out[4]: [u'ji1n', u'pi2ng', u'guo3']
```
