### ISSUE TITLE
关于禁用 “词组拼音库” 达到减少内存占用的问题

### ISSUE THREAD

**Issue by Provinm** [mozillazg/python-pinyin#113]
## 运行环境

* 操作系统（Linux/macOS/Windows）：windows
* Python 版本：2.7.10
* pypinyin 版本：0.25.0

## 问题描述以及解决过程

在我的项目中，汉字转拼音只会转单个的汉字，而不需要词组，如果不对 pypinyin 做任何改动直接导入 pinyin 会占用 30M 左右的内存

```
Line #    Mem usage    Increment   Line Contents
================================================
     7   25.246 MiB   25.246 MiB   @profile
     8                             def func():
     9   52.117 MiB   26.871 MiB       from pypinyin import pinyin,Style
    10   52.125 MiB    0.008 MiB       print pinyin(u'啦', style=Style.INITIALS)

```

通过给 mozillazg 大神发邮件询问，设置环境变量 `PYPINYIN_NO_PHRASES=true` 得以大量的减少了内存占用

设置代码

```python 

import os
os.environ['PYPINYIN_NO_PHRASES'] = 'true'

@profile
def func():
    from pypinyin import pinyin,Style
    print pinyin(u'啦', style=Style.INITIALS)

func()

```

最终的结果

```
Line #    Mem usage    Increment   Line Contents
================================================
     7   25.258 MiB   25.258 MiB   @profile
     8                             def func():
     9   29.176 MiB    3.918 MiB       from pypinyin import pinyin,Style
    10   29.184 MiB    0.008 MiB       print pinyin(u'啦', style=Style.INITIALS)

```

感谢大神的耐心回答，以上是整个问题解决过程，供有相似问题的同学作为参考。

**Comment by mozillazg** [comment]
感谢 @Provinm 分享这个需求，还可以通过删除 https://github.com/mozillazg/python-pinyin/blob/974350d9704ee2f35f99f0618948d3478dd6294f/pypinyin/constants.py#L22 这一行的 copy 方法调用来进一步减少内存占用：

```python
# 修改前
PINYIN_DICT = pinyin_dict.pinyin_dict.copy()
# 修改后
PINYIN_DICT = pinyin_dict.pinyin_dict
```

copy 的目的是希望在用户的自定义拼音库出现问题时可以回退到自带的拼音库，如果没有这个需求的话，可以禁用这个操作。

欢迎提交 PR 增加一种方法可以在不修改 pypinyin 代码的情况下实现禁用 copy 操作的目的（比如：增加 `PYPINYIN_NO_DICT_COPY` 或者 `PYPINYIN_DISABLE_DICT_COPY`  环境变量来控制）。

**Comment by daya0576** [comment]
> copy 的目的是希望在用户的自定义拼音库出现问题时可以回退到自带的拼音库

意思是说如果自定义的`PINYIN_DICT`出错的话, 用户可以自己调用`pinyin_dict.pinyin_dict`?

**Comment by mozillazg** [comment]
@daya0576 可以直接把 `PINYIN_DICT` 清空，然后用 `load_single_dict` 加载默认的 `pinyin_dict.pinyin_dict`，对于词组库也可以用类似的办法恢复（使用 `load_phrases_dict`）。

**Comment by crispgm** [comment]
Great! 恰好遇到这个问题 👍
