### ISSUE TITLE
字符"〇"不能正确转换

### ISSUE THREAD

**Issue by sidgwick** [mozillazg/python-pinyin#118]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Arch Linux x86_64
* Python 版本：Python 3.6.4
* pypinyin 版本：0.29.0

## 问题描述

字符 〇 不能正确转换.

## 问题复现步骤

```python
import pypinyin
print(pypinyin.lazy_pinyin("〇"));  # 输出: ['〇']
```

**Comment by mozillazg** [comment]
@sidgwick 感谢反馈。

**Comment by mozillazg** [comment]
@sidgwick 最新发布的 0.30.0 版本已经支持 `〇` 了。

**Comment by sidgwick** [comment]
刚才试了一下, 确实可以了. 辛苦

**Comment by zgdlime** [comment]
sidgwick
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！

**Comment by sidgwick** [comment]
@zgdlime 这个你读文件循环处理一下就解决了吧, 不太明白你说的拖叠是什么意思.
