### ISSUE TITLE
"不“ 出现在四声之前变二声的规则？

### ISSUE THREAD

**Issue by fynv** [mozillazg/python-pinyin#123]
## 运行环境

* 操作系统（Linux/macOS/Windows）： Windows
* Python 版本：3.6
* pypinyin 版本：0.30.0

## 问题描述
"不用“，”不必“ 等发音为”bu4 yo4ng", "bu4 bi4"
建议加入规则使其发为”bu2 yo4ng", "bu2 bi4"

**Comment by gumblex** [comment]
《汉语拼音正词法基本规则》里说

> 6.5.2 “一”、“不”一般标原调，不标变调。例如：…… bù duì（不对）

**Comment by fynv** [comment]
好吧，我其实是在用这个库做一个简易的TTS，所以需求出现偏差了。
Closing as not an issue.

**Comment by gumblex** [comment]
当然这个功能你可以自己包装实现一下。

**Comment by fynv** [comment]
还不那么容易，因为要知道拼音“bu4"来自“不"，还是“布”，还是“步”，要自己去输入中找到这个对应。。

**Comment by zgdlime** [comment]
@fynv
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！
