### ISSUE TITLE
No module named...

### ISSUE THREAD

**Issue by buzzgoing** [mozillazg/python-pinyin#124]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Mac OS
* Python 版本：3.6.0
* pypinyin 版本：0.30.0

## 问题描述
我用pip安装了pypinyin，并确定安装好了，可是不管怎么编译都说no module named pypinyin

**Comment by mozillazg** [comment]
@buzzgoing 

* 确认一下是否安装成功了：`pip freeze |grep pypinyin`
* 是否使用了虚拟环境，如果用了虚拟环境的话，确认是否使用虚拟环境中的 pip 和 python：

```
which pip
which python
```
