### ISSUE TITLE
是否支持使用尾随数字方式标识声调

### ISSUE THREAD

**Issue by butterl** [mozillazg/python-pinyin#127]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Linux
* Python 版本：python3.5
* pypinyin 版本：pypinyin-0.30.0

## 问题描述
是否支持类似如下的输出参数设置，使用尾随数字标识声调？

>>> from pypinyin import pinyin, lazy_pinyin, Style
>>> pinyin('中心')
[['zhong1'], ['xin1']]

**Comment by mozillazg** [comment]
@butterl `Style.TONE3` 这个拼音风格应该就是你说的【使用尾随数字标识声调】，你可以看一下：

```
pinyin('中心', style=Style.TONE3)
```

文档：https://pypinyin.readthedocs.io/zh_CN/master/api.html#pypinyin.Style.TONE3
