### ISSUE TITLE
书名《经纶济世》拼音标注错误

### ISSUE THREAD

**Issue by begeekmyfriend** [mozillazg/python-pinyin#128]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Ubuntu 16.04
* Python 版本：Python 3.6
* pypinyin 版本：0.30.1

## 问题描述
《经纶济世》四个字，合在一起，标注为轻声（无声调），每个字加上空格后，可以正确显示声调(1234)。

## 问题复现步骤

> (tensorflow) leoma@test-a2-60-75:~/python-pinyin_gitlab$ python 
> Python 3.6.4 |Anaconda, Inc.| (default, Dec 21 2017, 21:42:08) 
> [GCC 7.2.0] on linux
> Type "help", "copyright", "credits" or "license" for more information.
> \>\>\> from pypinyin import pinyin, lazy_pinyin, Style
> \>\>\> pinyin('经纶济世')
> [['jing'], ['lun'], ['ji'], ['shi']]
> \>\>\> pinyin('《经纶济世》')
> [['《'], ['jing'], ['lun'], ['ji'], ['shi'], ['》']]
> \>\>\> pinyin('《经纶 济世》')
> [['《'], ['jīng'], ['lún'], [' '], ['jì'], ['shì'], ['》']]
> \>\>\> pinyin('《经 纶 济 世》')
> [['《'], ['jīng'], [' '], ['lún'], [' '], ['jì'], [' '], ['shì'], ['》']]
>

**Comment by begeekmyfriend** [comment]
> >>> from pypinyin import pinyin, lazy_pinyin, Style
> \>\>\> pinyin('负债累累')
> [['fù'], ['zhai'], ['lèi'], ['lèi']]

**Comment by mozillazg** [comment]
@begeekmyfriend 感谢反馈！
