### ISSUE TITLE
拼音输出格式可以增加吗？

### ISSUE THREAD

**Issue by Holded** [mozillazg/python-pinyin#134]
比如音乐，现在的输出是'yi1n yue4'，桔子输出是'ju2 zi3'；有的音调标注会跑到中间去；
能否统一成'yin1 yue4'这样？
谢谢！

**Comment by mozillazg** [comment]
@Holded 已经内置了这种拼音风格：http://pypinyin.readthedocs.io/zh_CN/master/api.html#pypinyin.Style.TONE3
