### ISSUE TITLE
[一只]在句中的发音问题

### ISSUE THREAD

**Issue by xycui** [mozillazg/python-pinyin#135]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：3.5.4
* pypinyin 版本：0.31.0

## 问题描述
[一只]的发音问题：
eg1: 这是一只牧羊犬: expected: yi4 zhi1, actual **yi1 zhi1**
eg2: 他有一只牧羊犬: expected: yi4 zhi1, actual **yi1 zhi3**

**Comment by mozillazg** [comment]
@xycui 感谢反馈。我看一下。

**Comment by xycui** [comment]
后来我也看了一下，应该是分词的问题。第一个分词是 一只 第二个 一 和只被拆开了。

**Comment by mozillazg** [comment]
@xycui 最新版已经修复这个问题。

**Comment by zgdlime** [comment]
@xycui
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！
