### ISSUE TITLE
‘少’字的在某个词下返回声母x，韵母返回hao3

### ISSUE THREAD

**Issue by nerdmiao** [mozillazg/python-pinyin#136]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Ubuntu 16.04 LTS
* Python 版本：3.6
* pypinyin 版本：0.31.0

## 问题描述
‘少’字的在某个词下返回声母x，韵母返回hao3

## 问题复现步骤
错误：
>>> pinyin('缺吃少穿')
[['quē'], ['chī'], ['xhǎo'], ['chuān']]
>>> pinyin('缺吃少穿', style=Style.INITIALS)
[['q'], ['ch'], ['x'], ['ch']]
>>> pinyin('缺吃少穿', style=Style.FINALS_TONE3)
[['ue1'], ['i1'], ['hao3'], ['uan1']]
其他正确：
>>> pinyin('少', style=Style.INITIALS)
[['sh']]
>>> pinyin('吃少穿', style=Style.INITIALS)
[['ch'], ['sh'], ['ch']]

**Comment by mozillazg** [comment]
@nerdmiao 感谢反馈。

**Comment by mozillazg** [comment]
@nerdmiao 最新版已修复这个问题。

**Comment by zgdlime** [comment]
@nerdmiao
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！
