### ISSUE TITLE
拼音错误：三座大山中的大，输出的拼音是tai4

### ISSUE THREAD

**Issue by phoenixbai** [mozillazg/python-pinyin#137]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：2.7
* pypinyin 版本：0.31.0

Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05) 

## 问题描述
三座大山中的大，被拼出来是tai（太），不对。著名的著的拼音也错了吧
pinyin(u'三座大山', style=Style.FINALS.TONE3)
output: [[u'san1'], [u'zuo4'], [u'tai4'], [u'shan1']]

reduce(operator.concat, pinyin(u'世界著名', style=Style.FINALS.TONE3))
Out[110]: [u'shi4', u'jie4', u'**zhe**', u'ming2']

reduce(operator.concat, pinyin(u'严查', style=Style.FINALS.TONE3))
Out[111]: [u'yan2', u'zha1']

## 问题复现步骤
可复现。

thanks

**Comment by mozillazg** [comment]
@phoenixbai 感谢反馈！等我有空的时候看一下。

**Comment by zgdlime** [comment]
@phoenixbai
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！
