### ISSUE TITLE
命令行工具编码处理不好

### ISSUE THREAD

**Issue by Huarong** [mozillazg/python-pinyin#138]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Ubuntu 16.04.2 LTS
* Python 版本：2.7
* pypinyin 版本：0.32.0

## 问题描述

命令行工具编码处理不好

## 问题复现步骤

```
$ pypinyin 哈哈
Traceback (most recent call last):
  File "/usr/local/bin/pypinyin", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/pypinyin/runner.py", line 101, in main
    hans = options.hans.decode(sys.stdin.encoding)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe5 in position 0: ordinal not in range(128)
```

**Comment by mozillazg** [comment]
@Huarong 可以试一下指定一下编码：

```
$ PYTHONIOENCODING=utf-8 pypinyin 哈哈
```

**Comment by zgdlime** [comment]
@Huarong
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！
