### ISSUE TITLE
内置分词会导致部分输入得到非预期/不理想的结果

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/python-pinyin#139]
## 运行环境

* 操作系统（Linux/macOS/Windows）：macOS
* Python 版本：3.7
* pypinyin 版本：0.33.0

## 问题描述

内置的基于前缀匹配的最大正向匹配分词，会导致部分输入得到非预期/不理想的结果。

比如，https://github.com/mozillazg/python-pinyin/issues/135 这个问题：

> 
> [一只]的发音问题：
> eg1: 这是一只牧羊犬: expected: yi4 zhi1, actual yi1 zhi1
> eg2: 他有一只牧羊犬: expected: yi4 zhi1, actual yi1 zhi3

出现这个问题的原因是：词典中有 `有一天`、`一只` 的词语没有 `有一只` 这个词，此时 `有一只` 会分词成：`['有一', '只']`，分词分成 `['有', '一只']` 可能会更符合预期一点。

需要讨论一下是否有更好的解决方法。

## 相关 issue

* https://github.com/mozillazg/python-pinyin/issues/135
* https://github.com/mozillazg/phrase-pinyin-data/issues/19#issuecomment-414034412
* https://github.com/mozillazg/python-pinyin/pull/81
* https://github.com/mozillazg/phrase-pinyin-data/issues/12

**Comment by zgdlime** [comment]
@mozillazg 你封锁我的发言吗？ 请你帮写个运行 在Python处理b.txt文本汉字转拼音式子，会难为死你吗？

**Comment by zgdlime** [comment]
@mozillazg 你不理我，我会问别人去的。
