### ISSUE TITLE
多音字功能返回的发音有误

### ISSUE THREAD

**Issue by NingyanZhu** [mozillazg/python-pinyin#140]
## 运行环境

* 操作系统（Linux/macOS/Windows）：ubuntu16.04
* Python 版本：3.5.2
* pypinyin 版本：pypinyin-0.33.0

## 问题描述
在返回多音字结果模式下输出的结果并不完全属于原本文字的发音

## 问题复现步骤
print(pinyin("逐",style=Style.TONE3, heteronym=True))
print(pinyin("蹲",style=Style.TONE3, heteronym=True))
print(pinyin("景",style=Style.TONE3, heteronym=True))

输出结果：
[['zhu2', 'di2', 'zhou4', 'tun2']]
[['dun1', 'zun2', 'cun2', 'zun1', 'cun3', 'cuan2', 'qun3']]
[['jing3', 'ying3']]

**Comment by mozillazg** [comment]
@NingyanZhu 感谢反馈。

因为单个汉字的拼音数据是不同字典数据的合集，所以其中有些可能是平时很少用到的读音也有些可能是之前有这些读音只是最近几年大陆这边的字典不用了。比如 `蹲` 字在《汉语大字典》中是有很多读音的：

《汉语大字典》中的 `蹲` http://www.guoxuedashi.com/kangxi/pic.php?f=dzd&p=3988
（来源：http://www.guoxuedashi.com/zidian/8E72.html）

`逐` 跟 `蹲` 是一样的情况，`景` 在各大字典中应该都是两个音的。

当然其中也可能有些是有误的数据，欢迎帮忙一起维护拼音数据：

* 单个汉字的拼音：https://github.com/mozillazg/pinyin-data
* 词语的拼音：https://github.com/mozillazg/phrase-pinyin-data

**Comment by NingyanZhu** [comment]
原来是这样，谢谢解答～～

**Comment by zgdlime** [comment]
@NingyanZhu
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！

**Comment by JoffreyN** [comment]
>>> pypinyin.pinyin('澄清',heteronym=True)
[['chéng'], ['qīng']]
--------------------------------------------------------------------
澄清 有两种读音，dèngqīng 和 chéngqīng

**Comment by mozillazg** [comment]
@JoffreyN 感谢反馈，按照目前的设计处理不了这种一个词语多个读音的情况。
