### ISSUE TITLE
请问python-pinyin如何批量处理？

### ISSUE THREAD

**Issue by zgdlime** [mozillazg/python-pinyin#141]
运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？
@mozillazg @mozillazg @mozillazg @mozillazg @mozillazg

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！

**Comment by zgdlime** [comment]
@mozillazg 这个文本文件b.txt该如何操作？

**Comment by mozillazg** [comment]
@zgdlime 你可以看一下 Windows 批处理编程相关的知识。

**Comment by zgdlime** [comment]
@mozillazg 在Python，你就不能给一条式子处理b.txt吗？不给个样例怎样学习Python呢！

**Comment by zgdlime** [comment]
@mozillazg 请帮写个运行 在Python处理b.txt文本汉字转拼音式子（含参数）！
