### ISSUE TITLE
自定义拼音风格时，回调方法可以收到原始字符

### ISSUE THREAD

**Issue by LionGaokk** [mozillazg/python-pinyin#146]
希望自定拼音风格时，回调方法可以收到原始字符。
例 
@style.register('s1‘)
def style_s1(char, pinyin, **kw)
    return ……

主要想用于拼音排序后的二次排序，例如可输出 “pin1{笔划}yin1”这样的格式；
此时使用 slugn 转换字符串就很方便。

**Comment by mozillazg** [comment]
@LionGaokk 嗯，等我有空的时候看一下，同时也欢迎提交 PR。
