### ISSUE TITLE
自定义词库没有作用，需要enable吗？怎么做

### ISSUE THREAD

**Issue by jeremy886** [mozillazg/python-pinyin#15]
>>> from pypinyin import load_phrases_dict, lazy_pinyin, TONE2
>>> lazy_pinyin('还没', style = TONE2)
['hua2n', 'me2i']
>>> from pypinyin import load_phrases_dict, lazy_pinyin, TONE
>>> lazy_pinyin('还没', style = TONE)
['huán', 'méi']
>>> load_phrases_dict({'还没': [['hái'], ['méi']]})
>>> lazy_pinyin('还没', style = TONE)
['huán', 'méi']

**Comment by mozillazg** [comment]
@jeremy886 这个涉及到分词的问题。
如果你没有安装 jieba 分词模块，或者 `还没` 经过分词后不是一个词组的话，两种解决办法：

```python
>>>  load_phrases_dict({'还没': [['hái'], ['méi']]})
>>> lazy_pinyin(['还没'], style=TONE2)            # 手动指定 “还没” 为一个词组
['ha2i', 'me2i']
```
```python
>>> load_single_dict({ord('还'):'hái,huán'})      # 调整 ”还" 字的拼音顺序
>>> lazy_pinyin('还没', style=TONE2)
['ha2i', 'me2i']
```

**Comment by jeremy886** [comment]
Hi, I fixed it by doing pip upgrade.

All is good now.
