### ISSUE TITLE
如何判断分词列表是不是拼音？

### ISSUE THREAD

**Issue by wsyzzz** [mozillazg/python-pinyin#152]
您好，非常感谢您的项目！我现在的需求是判断一个**纯字母字符串**里包不包含拼音，有如下几个问题能麻烦您帮我看下吗？谢谢！

1、请问是否有function判断一个字符是否为拼音，如“nihao”,"shijie",“hello”--》True,True,False？

2、如果没有，我是否只能用phrase-pinyin-data项目下的large_pinyin.txt进行匹配了？感觉速度上会很慢

**Comment by mozillazg** [comment]
@wsyzzz 不客气。

> 1、请问是否有function判断一个字符是否为拼音，如“nihao”,"shijie",“hello”--》True,True,False？

目前没有这个功能。

> 2、如果没有，我是否只能用phrase-pinyin-data项目下的large_pinyin.txt进行匹配了？感觉速度上会很慢

可以分两步走，不会很慢：

1. 预处理：从 large_pinyin.txt 中提取出所有的拼音数据，去除音标，去重，得到一个拼音集合
2. 后续就通过这个集合来判断字符串是否是拼音。这一步的方法有很多，比如直接用
   `set/list/tuple/dict` 的 `in` 表达式或把第一步的数据存到 db/kv 中直接查询或用一些字符串匹配/搜索方面的算法。
