### ISSUE TITLE
如何引用这项工作？

### ISSUE THREAD

**Issue by fuzixiansheng** [mozillazg/python-pinyin#153]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：
* pypinyin 版本：

## 问题描述
您好，非常好的工作，对我们帮助很大。我们是想根据文本生成一些语音，首先需要将文本转化为拼音，试了一下你们的工具，效果比其他的工具都好。我们也打算用这个，目前的问题是如果顺利形成文章的话，该如何引用你们的工作呢？

**Comment by mozillazg** [comment]
@fuzixiansheng 很高兴这个项目对你有所帮助。

关于引用的问题，https://zenodo.org/ 是否可以？等我周末的时候发一个版本到 zenodo.org 上面，然后直接引用 zenodo 提供的 DOI 信息 。

**Comment by fuzixiansheng** [comment]
好的，麻烦您了，非常感谢您！

**Comment by mozillazg** [comment]
@fuzixiansheng 已上传 zenodo: https://zenodo.org/record/2528923

P.S. 简单了解了一下，发现大家在 paper 中引用软件之类的资源一般用的都是 `<软件名称>. <官网链接>.` 的方式，好像基本不会去用 DOI 信息，你可以参考一下。

比如下面这些仓库中列出的 paper:
* https://github.com/shadowsocks/papers
* https://github.com/aleju/papers
* https://github.com/papers-we-love/papers-we-love
* https://github.com/jtoy/awesome-tensorflow#papers

参考上面的 paper，也可以用下面任一条引用这个项目（具体用哪种方式你可以咨询你的导师听听他/她的意见）：

* `pypinyin. https://github.com/mozillazg/python-pinyin.`
* `pypinyin. 2018. https://github.com/mozillazg/python-pinyin. (2018).`
* `pypinyin. (2018, Dec.) pypinyin webpage. [Online]. Available:
https://github.com/mozillazg/python-pinyin.`
* `Mozillazg. 2018. pypinyin. https://github.com/mozillazg/python-pinyin. (2018).`

**Comment by mozillazg** [comment]
@fuzixiansheng 也可以参考一下已有的 paper 中是如何引用这个项目的：

* https://scholar.google.com/scholar?q=python-pinyin
* https://scholar.google.com/scholar?q=pypinyin

**Comment by fuzixiansheng** [comment]
好的！非常感谢您的工作以及帮助！
解释非常的详细具体，我已经知道如何引用您的工作了，希望早日能够做完实验，成功引用您的文章~
麻烦您了，新年快乐~

**Comment by mozillazg** [comment]
@fuzixiansheng 不客气。新年快乐~
