### ISSUE TITLE
朝阳多音词错误

### ISSUE THREAD

**Issue by demonkit** [mozillazg/python-pinyin#154]
## 运行环境

* 操作系统（Linux/macOS/Windows）：macOS
* Python 版本：2.7.10
* pypinyin 版本：0.34.0

## 问题描述
词组：朝阳，读音是多音词，有zhaoyang、chaoyang两种读法，使用多音词只返回一种读法。

## 问题复现步骤
直接调用代码即可出现。
```
>>> pinyin(u"朝阳", heteronym=True, style=Style.NORMAL)
[[u'zhao'], [u'yang']]
```

**Comment by mozillazg** [comment]
@demonkit 感谢反馈~ 待我有空的时候看看。

**Comment by mozillazg** [comment]
Fixed via https://github.com/mozillazg/python-pinyin/commit/c22f8e83ceb8c358396199dace0ac69942b14a98

**Comment by mozillazg** [comment]
最新版已解决这个问题
