### ISSUE TITLE
数据有错误，比如：方

### ISSUE THREAD

**Issue by liuyug** [mozillazg/python-pinyin#155]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本： python3
* pypinyin 版本： 0.34.1

## 问题描述
更新新版后，数据有错误

## 问题复现步骤

$ pypinyin -V
pypinyin 0.34.1
$ pypinyin --heteronym 方
fāng,fáng,fǎng,páng,wǎng,fēng

**Comment by mozillazg** [comment]
@liuyug 感谢反馈~ 待我有空的时候看看。

**Comment by mozillazg** [comment]
@liuyug 《汉语大字典》中有这些读音，详见：http://www.guoxuedashi.com/kangxi/pic.php?f=dzd&p=2328

**Comment by liuyug** [comment]
《汉语大字典》中有 “方羊” 方读 páng，也作“彷徉”。现代汉语与古代汉语有很大区别，好多字词已经不用，或者被新的字词代替。

在做 Pinyin 数据时，是否需要考虑常见，生僻，和替代等，确定一个数据范围，加入一个数据范围选项。

比如中国汉字标准，GB2312， GB18030，GBK

字典也有好多种，比如《现代汉语词典》，《古代汉语

Pinyin 数据 是否也需要区分下？

**Comment by mozillazg** [comment]
@liuyug 要区分的话需要解决下面的问题：

* 数据源问题：需要有权威的拼音和汉字信息数据源。
* 人力问题：这个工作耗时耗力，工作量非常大，需要大家群策群力。

精力有限暂时不打算做这个。
