### ISSUE TITLE
lazy_pinyin('佛')返回fu

### ISSUE THREAD

**Issue by lrhhhhhh** [mozillazg/python-pinyin#156]
## 运行环境

* 操作系统（Linux/macOS/Windows）：ubuntu16.04
* Python 版本：3.5.2
* pypinyin 版本：0.34.1

## 问题描述
lazy_pinyin('佛')返回拼音fu

**Comment by mozillazg** [comment]
没理解问题是啥

**Comment by lrhhhhhh** [comment]
@mozillazg 
lazy_pinyin()这个函数，'佛'这个字返回fu

**Comment by Sundy1219** [comment]
＠lrhhhhhh 　单个＇佛＇字，返回这个'fu'，应该没问题，比如＇仿佛＇，是可以有这个音的

**Comment by lrhhhhhh** [comment]
> ＠lrhhhhhh 　单个＇佛＇字，返回这个'fu'，应该没问题，比如＇仿佛＇，是可以有这个音的

我失了智..
