### ISSUE TITLE
拼音出错

### ISSUE THREAD

**Issue by Sundy1219** [mozillazg/python-pinyin#157]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Linux
* Python 版本：2.7
* pypinyin 版本：pypinyin-0.35.1

## 问题描述
１调低一度，调高一度，调大一点，调小一点，调优，下调，中的'调':拼成了diao4

 2 增大九度，减小六度中'九,六'，采用pinyin(txt, style=Style.FINALS_TONE3)得到韵母时,所有的iu3都变成了iou3

 3 智慧的＇慧＇字,采用pinyin(txt, style=Style.FINALS_TONE3)得到韵母时,ui4变成了uei4，我发现从0.30.0版本后就会出错,包括上一问也是

 ４ 农业银行总行:拼成了
[[u'nong2'], [u'ye4'], [u'yin2'], [u'hang2'], [u'zong3'], [u'xing2']]
最后一个"行"字音错了

**Comment by mozillazg** [comment]
> １调低一度，调高一度，调大一点，调小一点，调优，下调，中的'调':拼成了diao4
> ４ 农业银行总行:拼成了

这个目前没有特别好的一劳永逸的解决办法，可以通过自定义词库的方式 case by case 解决一下：https://pypinyin.readthedocs.io/zh_CN/master/usage.html#custom-dict

> 2 增大九度，减小六度中'九,六'，采用pinyin(txt, style=Style.FINALS_TONE3)得到韵母时,所有的iu3都变成了iou3
> 3 智慧的＇慧＇字,采用pinyin(txt, style=Style.FINALS_TONE3)得到韵母时,ui4变成了uei4，我发现从0.30.0版本后就会出错,包括上一问也是

因为按照《汉语拼音方案》韵母就是那个，如果不想遵循《汉语拼音方案》的话可以设置 `struct` 参数的值为 `False` 详见：https://pypinyin.readthedocs.io/zh_CN/master/usage.html#strict

**Comment by Sundy1219** [comment]
谢谢的回复，自定义词库的方式，我尝试了，是可以用的，可以一个标错的，就加一行load_phrases_dict代码，那如果有成百上千个错误，那不得手动写很多行，代码太冗余了，我想说，能不能在某个文件中，写上正确的标注，直接加载这个文件？谢谢

**Comment by mozillazg** [comment]
@Sundy1219 load_phrases_dict 接受的参数是一个 dict ，对这个 dict 中 key 的数量没有做限制，所以是可以一次性加载成千上万个修正数据的，不需要调用多次。至于加载某个文件中修正数据的功能你可以在你的程序里简单封装一下来实现这个需求。
