### ISSUE TITLE
pypinyin安装后引入unique error

### ISSUE THREAD

**Issue by cold2wind** [mozillazg/python-pinyin#158]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Linux
* Python 版本：2.7.9
* pypinyin 版本：0.35.1

## 问题描述
   使用报错
   from pypinyin import lazy_pinyin, pinyin, Style
   from pypinyin.constants import (  # noqa
   from enum import IntEnum, unique
       ImportError: cannot import name unique
## 问题复现步骤
   from pypinyin import lazy_pinyin, pinyin, Style

def query_2_pinyin(query=''):
    segment = lazy_pinyin(query)
    join_pinyin = ''.join(segment)
    prefix_pinyin_list = pinyin(query, style=Style.FIRST_LETTER)

**Comment by mozillazg** [comment]
@cold2wind 可能是你装了一个叫 enum 的包跟 pypinyin 依赖的 enum34 这个包冲突了（他们的用法都是 import enum）。建议把 enum 给卸载了（enum34 的功能是 enum 这个包的超集，所以卸载是没问题的）。
