### ISSUE TITLE
"鸟事“错误转换为”niao sh"

### ISSUE THREAD

**Issue by ledao** [mozillazg/python-pinyin#159]
## 运行环境

* 操作系统（Linux/macOS/Windows）：win10
* Python 版本：3.6.5
* pypinyin 版本：0.33.2

## 问题描述
"鸟事“错误转换为”niao sh"

## 问题复现步骤
from pypinyin import lazy_pinyin
lazy_pinyin("鸟事")
==>['niao', 'sh']

**Comment by mozillazg** [comment]
@ledao 感谢反馈。待我有空的时候修复一下。

**Comment by ledao** [comment]
先别关闭issue，我再测试一下，把有错误的都贴上来

**Comment by ledao** [comment]
发现新的错误，如下所示：
>>> lazy_pinyin("虮虱相吊")
['ji', 'shi', 'xieng', 'diao']

>>> lazy_pinyin("别鹤离鸾")
['bie', 'he', 'li', 'laun']

>>> lazy_pinyin("年华垂暮")
['nian', 'hua', 'thui', 'mu']

>>> lazy_pinyin("本枝百世")
['ben', 'zhi', 'boi', 'shi']

>>> lazy_pinyin("操戈同室")
['cao', 'ge', 'toon', 'shi']

>>> lazy_pinyin("丢魂丧胆")
['diu1', 'hun', 'sang', 'dan']

**Comment by mozillazg** [comment]
@ledao 感谢测试。冒昧问一下，是否方便透露你测试时使用比对数据源，我看看能否通过这个数据源找到更多的异常拼音。

**Comment by ledao** [comment]
抱歉，这个语料无法共享～我们数据源已经跑完了，所有错误都已列出。

**Comment by mozillazg** [comment]
@ledao 抱歉，是我冒昧了才是。感谢分享你们发现的错误。我周末会发布一个版本修复一下这个 issue 中提到的问题。

**Comment by mozillazg** [comment]
@ledao 最新版已修复这个 issue 提到的所有有问题的拼音。
