### ISSUE TITLE
晚节不保中的"节"的读音错了

### ISSUE THREAD

**Issue by phoenixbai** [mozillazg/python-pinyin#160]
## 运行环境
Python 2.7.15 |Anaconda, Inc.| (default, May  1 2018, 18:37:05)
[GCC 4.2.1 Compatible Clang 4.0.1 (tags/RELEASE_401/final)] on darwin
pypinyin.__version__ :  0.33.2

## 问题描述
如下, 节字的读音返回的是[u'ji2e'] , 肯定是错的, 应该是[u'jie2']. 
若只有'晚节'时, 都是对的, 变成'晚节不保', 就错了. 好奇怪.
卉 字的读音也是错的
希望能尽快修复一下.
```
from pypinyin import pinyin, lazy_pinyin, Style
words=u'晚节不保'
pinyins = pinyin(words, style=Style.TONE2, heteronym=True)
pinyins
[[u'wa3n'], [u'ji2e'], [u'bu4'], [u'ba3o']]

words=u'奇葩异卉'
<type 'list'>: [[u'qi2'], [u'pa1'], [u'yi4'], [u'hu4i']]
```

thanks

**Comment by mozillazg** [comment]
@phoenixbai 感谢反馈。我周末修复一下。如果着急的话可以通过 https://pypinyin.readthedocs.io/zh_CN/master/usage.html#custom-dict 这里的方法临时解决一下。

**Comment by phoenixbai** [comment]
这是拼音音调放错位置了, 所以我根据下面标准, 对输出的拼音的音调, 统一做了个纠正. 问题临时性地解决了.

> 有ɑ不放过（有ɑ一定要标在ɑ上）；无ɑ找oe（没有ɑ的时候标在o上,如果没有o则标在e上）iu并列标在后（iu, ui的情况,标在后面的字母上,比如说iu应该标u,ui应该标i）；单个韵母不用说（只能标在单韵母上）

**Comment by mozillazg** [comment]
@phoenixbai 感谢分享你的方法，最新版已经用这个规则检查并修复了所有有问题的拼音。
