### ISSUE TITLE
Is it possible to support cedict compatible pinyin format?

### ISSUE THREAD

**Issue by hanabi1224** [mozillazg/python-pinyin#165]
cedict 考虑了例如儿化音
`兒/儿 is an optional northern pronunciation (er2hua4) and is tacked on to the preceding syllable - 花兒/花儿 huār (flower) as opposed to 花 huā (flower)`
`一下兒 一下儿 [yi1 xia4 r5] /erhua variant of 一下[yi1 xia4]/`

References: 
https://cc-cedict.org/wiki/format:syntax
https://www.mdbg.net/chinese/dictionary?page=cc-cedict

**Comment by mozillazg** [comment]
暂时不打算支持。如果是儿化音的话，打算等 https://github.com/mozillazg/python-pinyin/issues/162 完成后再支持。目前用户要支持儿化音的话就是需要用户对结果自行做二次处理。

**Comment by hanabi1224** [comment]
@mozillazg  看了一下目前的字典是把儿化的er标成轻声，这样其实也行， cc-cedict字典里有几百个儿化音的词，可不可以把字典更新一下呢？  cc-cedict的license有问题吗？ 
[Creative Commons License](https://creativecommons.org/licenses/by-sa/4.0/)
This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License. (click the link for detailed information)
It more or less means that you are allowed to use this data for both non-commercial and commercial purposes provided that you: mention where you got the data from (attribution) and that in case you improve / add to the data you will share these changes under the same license (share alike).
https://cc-cedict.org/editor/editor.php?handler=Download

**Comment by mozillazg** [comment]
Closed via https://github.com/mozillazg/phrase-pinyin-data/pull/21
