### ISSUE TITLE
“城市建设用地”中的“地”，“亲力亲为”中的“为”拼音错误。

### ISSUE THREAD

**Issue by hubeibei007** [mozillazg/python-pinyin#166]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Linux
* Python 版本：3.5
* pypinyin 版本：0.34.1

## 问题描述
“城市建设用地”中的“地”拼音错误

## 问题复现步骤
from pypinyin import pinyin
pinyin("城市建设用地")

[['chéng'], ['shì'], ['jiàn'], ['shè'], ['yòng'], ['de']]

"城市建设用地"中的“地”拼音转成了‘de’

pinyin("亲力亲为")
[['qīn'], ['lì'], ['qīn'], ['wèi']]

应该是wei2，第二声。

**Comment by mozillazg** [comment]
感谢反馈！词组这个不大好处理，目前是 case by case 的通过词组拼音库的方式解决的，我抽空更新一下词组拼音库。
