### ISSUE TITLE
invalid pinyin syllable "bia" for "柏"

### ISSUE THREAD

**Issue by wizardk** [mozillazg/python-pinyin#167]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Win10
* Python 版本：3.6.6
* pypinyin 版本：0.35.2

## 问题描述
got an invalid pinyin syllable "bia" from "柏"

## 问题复现步骤
from pypinyin import pinyin, Style
pinyin('后遍游道教名山常餐松啖柏舍物济人', style=Style.NORMAL)

[['hou'], ['bian'], ['you'], ['dao'], ['jiao'], ['ming'], ['shan'], ['chang'], ['can'], ['song'], ['dan'], ['**bia**'], ['she'], ['wu'], ['ji'], ['ren']]

**Comment by mozillazg** [comment]
感谢反馈！

**Comment by mozillazg** [comment]
Fixed via bfb1060
