### ISSUE TITLE
invalid pinyin syllable "n" for "嗯"

### ISSUE THREAD

**Issue by wizardk** [mozillazg/python-pinyin#168]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Win10
* Python 版本：3.6.6
* pypinyin 版本：0.35.2

## 问题描述
got an invalid pinyin syllable "n" from "嗯"

## 问题复现步骤
from pypinyin import pinyin, Style
pinyin('你如何里嗯你如何理解这一观点', style=Style.NORMAL)

[['ni'], ['ru'], ['he'], ['li'], ['**n**'], ['ni'], ['ru'], ['he'], ['li'], ['jie'], ['zhe'], ['yi'], ['guan'], ['dian']]

**Comment by mozillazg** [comment]
嗯这个没错，详见：https://github.com/mozillazg/python-pinyin/issues/109

**Comment by wizardk** [comment]
好的，多谢，另外，如果需要分担支持，可以告诉我
