### ISSUE TITLE
invalid pinyin syllable "f" for "逢"

### ISSUE THREAD

**Issue by wizardk** [mozillazg/python-pinyin#169]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Win10
* Python 版本：3.6.6
* pypinyin 版本：0.35.2

## 问题描述
got an invalid pinyin syllable "f" from "逢"

## 问题复现步骤
from pypinyin import pinyin, Style
pinyin('人生何处不相逢我要听这首歌', style=Style.NORMAL)

[['ren'], ['sheng'], ['he'], ['chu'], ['bu'], ['xiang'], ['**f**'], ['wo'], ['yao'], ['ting'], ['zhe'], ['shou'], ['ge']]

**Comment by mozillazg** [comment]
感谢反馈！

**Comment by mozillazg** [comment]
Fixed via bfb1060
