### ISSUE TITLE
invalid pinyin syllable "xv" for "徐"

### ISSUE THREAD

**Issue by wizardk** [mozillazg/python-pinyin#170]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Win10
* Python 版本：3.6.6
* pypinyin 版本：0.35.2

## 问题描述
got an invalid pinyin syllable "xv" from "徐"

## 问题复现步骤
from pypinyin import pinyin, Style
pinyin('吾与城北徐公孰美的孰啥意思', style=Style.NORMAL)

[['wu'], ['yu'], ['cheng'], ['bei'], ['**xv**'], ['gong'], ['shu'], ['mei'], ['de'], ['shu'], ['sha'], ['yi'], ['si']]

**Comment by mozillazg** [comment]
无声调相关拼音风格下的结果会使用 `v` 表示 `ü`

**Comment by gumblex** [comment]
j q x 用 u 吧

**Comment by mozillazg** [comment]
@gumblex 嗯，又看了一下，是 `徐` 的拼音错了，标成了 `xǘ`

**Comment by mozillazg** [comment]
Fixed via bfb1060
