### ISSUE TITLE
u'用'转拼音时，style=Style.INITIALS  结果为空

### ISSUE THREAD

**Issue by thesby** [mozillazg/python-pinyin#171]
Python 2.7.2
pypinyin 版本 0.35.2
```
print pinyin(u'用', style=Style.INITIALS)
[[u'']]
```

**Comment by gumblex** [comment]
https://github.com/mozillazg/python-pinyin#%E4%B8%BA%E4%BB%80%E4%B9%88%E6%B2%A1%E6%9C%89-y-w-yu-%E5%87%A0%E4%B8%AA%E5%A3%B0%E6%AF%8D

**Comment by thesby** [comment]
明白了，谢谢
