### ISSUE TITLE
多音字的拼音不准确

### ISSUE THREAD

**Issue by zjryan** [mozillazg/python-pinyin#173]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：2.7.9
* pypinyin 版本：0.24.0

## 问题描述
多音字拼音不准确
比如最并没有cuo这个音
撮也没有这么多音

## 问题复现步骤
 In [2]: pypinyin.pinyin(u'撮', style=pypinyin.TONE2, heteronym=True)
Out[2]: [[u'cuo1', u'zui4', u'zua1n', u'chua1', u'zuo3']]

In [3]: pypinyin.pinyin(u'最', style=pypinyin.TONE2, heteronym=True)
Out[3]: [[u'zui4', u'cuo1']]

**Comment by zjryan** [comment]
多音字能否更换数据源？只使用常见的多音字就可以了

**Comment by mozillazg** [comment]
@zjryan 嗯，问题是没有找到更权威的电子版可编辑的数据源，现在用的已经是国际上比较权威的数据源了（基于 Unicode 组织的 [Unihan Database](http://www.unicode.org/charts/unihan.html) 数据源），详见：https://github.com/mozillazg/pinyin-data

**Comment by zjryan** [comment]
> @zjryan 嗯，问题是没有找到更权威的电子版可编辑的数据源，现在用的已经是国际上比较权威的数据源了（基于 Unicode 组织的 [Unihan Database](http://www.unicode.org/charts/unihan.html) 数据源），详见：https://github.com/mozillazg/pinyin-data

这个项目我也看了，我现在的解决方案是自己reload了一下zdic.txt文件
希望以后能有个内置的数据源切换功能
