### ISSUE TITLE
在phrase-pinyin-data/pinyin.txt (A)里面有，但是不在 pinyin-data/pinyin.txt (B) 里面的拼音 有80个拼音，207个词

### ISSUE THREAD

**Issue by linzehua** [mozillazg/python-pinyin#174]
在phrase-pinyin-data/pinyin.txt (A)里面有，但是不在 pinyin-data/pinyin.txt (B) 里面的拼音
有80个拼音，207个词

(行号， 词语，A中标注的拼音，不在B中的拼音)
(2, '一丁点儿', ['yī', 'dīng', 'diǎn', 'er'], 'er')
(46, '一会儿', ['yī', 'huì', 'er'], 'er')
(124, '一回儿', ['yì', 'huí', 'er'], 'er')
(276, '一时半会儿', ['yī', 'shí', 'bàn', 'huì', 'er'], 'er')
(423, '一股劲儿', ['yī', 'gǔ', 'jìn', 'er'], 'er')
(566, '丁点儿', ['dīng', 'diǎn', 'er'], 'er')
(716, '万贯家私', ['wàn', 'guàn', 'ji', 'sī'], 'ji')
(1179, '不一会儿', ['bù', 'yī', 'huì', 'er'], 'er')
(1222, '不亦善夫', ['bù', 'yi', 'shàn', 'fū'], 'yi')
(1301, '不分青白', ['bù', 'fēn', 'qīng', 'béi'], 'béi')
(1450, '不奈之何', ['bù', 'nai', 'zhī', 'hé'], 'nai')
(1736, '不点儿', ['bù', 'diǎn', 'er'], 'er')
(1992, '不贪为宝', ['bù', 'tān', 'wé', 'bǎo'], 'wé')
(2083, '不随以止', ['bu', 'shui', 'yi', 'zi'], 'bu')
(2083, '不随以止', ['bu', 'shui', 'yi', 'zi'], 'yi')
(2126, '与时消息', ['yǔ', 'shí', 'xiāo', 'xi'], 'xi')
(2256, '东方将白', ['dong', 'fang', 'jiang', 'bai'], 'dong')
(2275, '东西南北人', ['dōng', 'xi', 'nán', 'běi', 'rén'], 'xi')
(2276, '东西南北客', ['dōng', 'xi', 'nán', 'běi', 'kè'], 'xi')
(2312, '丢下耙儿弄扫帚', ['diū', 'xià', 'pá', 'er', 'nòng', 'sào', 'zhǒu'], 'er')
(2424, '个头儿', ['gè', 'tou', 'er'], 'er')
(4257, '会儿', ['huì', 'er'], 'er')
(4487, '伺候', ['cì', 'hou'], 'hou')
(4572, '体己', ['tī', 'ji'], 'ji')
(4806, '侄儿', ['zhí', 'er'], 'er')
(4808, '侄女儿', ['zhí', 'nǚ', 'er'], 'er')
(5080, '信皮儿', ['xìn', 'pí', 'er'], 'er')
(5162, '倒儿爷', ['dǎo', 'er', 'yé'], 'er')
(5525, '傻劲儿', ['shǎ', 'jìn', 'er'], 'er')
(5694, '兔角龟毛', ['tu', 'jiao', 'gui', 'mao'], 'gui')
(5694, '兔角龟毛', ['tu', 'jiao', 'gui', 'mao'], 'mao')
(6520, '冲劲儿', ['chòng', 'jìn', 'er'], 'er')
(6549, '冲盹儿', ['chòng', 'dǔn', 'er'], 'er')
(7882, '动弹', ['dòng', 'tan'], 'tan')
(7931, '努劲儿', ['nǔ', 'jìn', 'er'], 'er')
(7941, '劲儿', ['jìn', 'er'], 'er')
(8083, '包馄饨', ['bāo', 'hún', 'tun'], 'tun')
(8621, '单口相声', ['dān', 'kǒu', 'xiàng', 'sheng'], 'sheng')
(9218, '叉儿', ['chā', 'er'], 'er')
(9726, '叨叨', ['dāo', 'dao'], 'dao')
(10087, '吆喝', ['yāo', 'he'], 'he')
(10199, '吊儿郎当', ['diào', 'er', 'láng', 'dāng'], 'er')
(10201, '吊尔郎当', ['diào', 'er', 'láng', 'dāng'], 'er')
(10355, '同源异派', ['tóng', 'yuán', 'yì', 'pai'], 'pai')
(10436, '名我固当', ['ming', 'wo', 'gu', 'dang'], 'wo')
(10524, '吗玩意儿', ['má', 'wán', 'yì', 'er'], 'er')
(10642, '吵吵', ['chāo', 'chao'], 'chao')
(10643, '吵吵闹闹', ['chāo', 'chao', 'nào', 'nào'], 'chao')
(11077, '哥们儿', ['gē', 'men', 'er'], 'er')
(11078, '哥儿们', ['gē', 'er', 'men'], 'er')
(11089, '哪会儿', ['něi', 'huì', 'er'], 'er')
(11099, '哭丧', ['kū', 'sang'], 'sang')
(11100, '哭丧棒', ['kū', 'sang', 'bàng'], 'sang')
(11154, '唱片儿', ['chàng', 'piān', 'er'], 'er')
(11228, '喊倒好儿', ['hǎn', 'dào', 'hǎo', 'er'], 'er')
(11397, '嚏喷', ['tì', 'pen'], 'pen')
(11399, '嚷嚷', ['rāng', 'rang'], 'rang')
(12430, '多会儿', ['duō', 'huì', 'er'], 'er')
(12438, '多口相声', ['duō', 'kǒu', 'xiàng', 'sheng'], 'sheng')
(12511, '够劲儿', ['gòu', 'jìn', 'er'], 'er')
(12545, '大人先生', ['dà', 'rén', 'xiān', 'sheng'], 'sheng')
(12852, '大明法度', ['dà', 'jíng', 'fǎ', 'dù'], 'jíng')
(13247, '天宝当年', ['tian', 'bao', 'dang', 'nian'], 'tian')
(13247, '天宝当年', ['tian', 'bao', 'dang', 'nian'], 'bao')
(13247, '天宝当年', ['tian', 'bao', 'dang', 'nian'], 'nian')
(13428, '失败为成功之母', ['shī', 'bài', 'wéi', 'chéng', 'gōng', 'zhī', 'm'], 'm')
(13442, '头会箕敛', ['tóu', 'kuàn', 'jī', 'liǎn'], 'kuàn')
(13445, '头儿', ['tou', 'er'], 'er')
(13718, '奔头儿', ['bèn', 'tou', 'er'], 'er')
(14014, '如之奈何', ['rú', 'zhī', 'nai', 'hé'], 'nai')
(14134, '妞儿', ['niū', 'er'], 'er')
(14242, '娶媳妇儿', ['qǔ', 'xí', 'fu', 'er'], 'er')
(14257, '媳妇儿', ['xí', 'fu', 'er'], 'er')
(14928, '宽绰', ['kuān', 'chuo'], 'chuo')
(15046, '寸劲儿', ['cùn', 'jìn', 'er'], 'er')
(15078, '对口相声', ['duì', 'kǒu', 'xiàng', 'sheng'], 'sheng')
(15255, '小不点儿', ['xiǎo', 'bù', 'diǎn', 'er'], 'er')
(15288, '小妞儿', ['xiǎo', 'niū', 'er'], 'er')
(15381, '少奶奶', ['shào', 'nǎi', 'nai'], 'nai')
(15431, '尕驴儿', ['gǎ', 'lǘ', 'er'], 'er')
(15951, '差一点儿', ['chà', 'yì', 'diǎn', 'er'], 'er')
(16419, '广文先生', ['guǎng', 'wén', 'xiān', 'sheng'], 'sheng')
(16553, '底片儿', ['dǐ', 'piān', 'er'], 'er')
(16851, '弟弟', ['dì', 'di'], 'di')
(17104, '当务始终', ['dang', 'wu', 'shi', 'zhong'], 'zhong')
(17108, '当口儿', ['dāng', 'kǒu', 'er'], 'er')
(17235, '影片儿', ['yǐng', 'piān', 'er'], 'er')
(17684, '思所逐之', ['si', 'shuo', 'zhu', 'zi'], 'shuo')
(17684, '思所逐之', ['si', 'shuo', 'zhu', 'zi'], 'zhu')
(17839, '恩不放债', ['ēn', 'bù', 'fàng', 'zhai'], 'zhai')
(18121, '惨绿愁红', ['cǎn', 'lü', 'chóu', 'hóng'], 'lü')
(18154, '愁红惨绿', ['chóu', 'hóng', 'cǎn', 'lü'], 'lü')
(19164, '折而族之', ['zhe', 'er', 'zu', 'zi'], 'er')
(19164, '折而族之', ['zhe', 'er', 'zu', 'zi'], 'zu')
(19380, '担担面', ['dàn', 'dan', 'miàn'], 'dan')
(19496, '拍片儿', ['pāi', 'piān', 'er'], 'er')
(19687, '拱肩缩背', ['gǒng', 'jān', 'suō', 'bèi'], 'jān')
(19721, '拾掇无遗', ['shi', 'duo', 'wu', 'yi'], 'yi')
(19939, '挨家挨户', ['āi', 'ji', 'āi', 'hù'], 'ji')
(20302, '揣手儿', ['chuāi', 'shǒu', 'er'], 'er')
(20671, '攒眉蹙额', ['cuán', 'mei', 'cù', 'é'], 'mei')
(20686, '支分族解', ['zhī', 'fē', 'zú', 'jiě'], 'fē')
(21065, '数理逻辑', ['shù', 'lǐ', 'luó', 'ji'], 'ji')
(21084, '数黄道黑', ['shu', 'huang', 'dao', 'hei'], 'shu')
(21084, '数黄道黑', ['shu', 'huang', 'dao', 'hei'], 'dao')
(21084, '数黄道黑', ['shu', 'huang', 'dao', 'hei'], 'hei')
(21230, '斗箕', ['dòu', 'ji'], 'ji')
(21573, '无寇暴死', ['wu', 'kou', 'bào', 'shi'], 'kou')
(22460, '曾不惨然', ['zeng', 'bu', 'chan', 'ran'], 'zeng')
(22460, '曾不惨然', ['zeng', 'bu', 'chan', 'ran'], 'bu')
(22460, '曾不惨然', ['zeng', 'bu', 'chan', 'ran'], 'chan')
(22460, '曾不惨然', ['zeng', 'bu', 'chan', 'ran'], 'ran')
(22494, '月头儿', ['yuè', 'tou', 'er'], 'er')
(23933, '桑葚儿', ['sāng', 'rèn', 'er'], 'er')
(24360, '歌片儿', ['gē', 'piān', 'er'], 'er')
(24608, '死劲儿', ['sǐ', 'jìng', 'er'], 'er')
(24950, '水中捉月', ['shui', 'zhong', 'zhuo', 'yue'], 'zhong')
(24950, '水中捉月', ['shui', 'zhong', 'zhuo', 'yue'], 'yue')
(25122, '汗褂儿', ['hàn', 'guà', 'er'], 'er')
(25132, '汝成人耶', ['nu', 'cheng', 'ren', 'ye'], 'nu')
(25132, '汝成人耶', ['nu', 'cheng', 'ren', 'ye'], 'cheng')
(25132, '汝成人耶', ['nu', 'cheng', 'ren', 'ye'], 'ren')
(25186, '汹涌彭湃', ['xiōng', 'yǒng', 'péng', 'pai'], 'pai')
(25187, '汹涌淜湃', ['xiōng', 'yǒng', 'péng', 'pai'], 'pai')
(25297, '沙鸥翔集', ['sha', 'ou', 'xiang', 'ji'], 'xiang')
(25297, '沙鸥翔集', ['sha', 'ou', 'xiang', 'ji'], 'ji')
(25329, '没头苍蝇', ['méi', 'tóu', 'cāng', 'ying'], 'ying')
(25371, '没谱儿', ['méi', 'pǔ', 'er'], 'er')
(25799, '活儿', ['huó', 'er'], 'er')
(25967, '浑球儿', ['hún', 'qiú', 'er'], 'er')
(26268, '混球儿', ['hùn', 'qiú', 'er'], 'er')
(26825, '炮子儿', ['pào', 'zǐ', 'er'], 'er')
(27205, '爪尖儿', ['zhuǎ', 'jiān', 'er'], 'er')
(27258, '片儿', ['piān', 'er'], 'er')
(27259, '片儿汤', ['piān', 'er', 'tāng'], 'er')
(28183, '男孩儿', ['nán', 'hái', 'er'], 'er')
(28211, '画片儿', ['huà', 'piān', 'er'], 'er')
(28963, '相声', ['xiàng', 'sheng'], 'sheng')
(29043, '相片儿', ['xiàng', 'piān', 'er'], 'er')
(29513, '矫矫不群', ['jiǎo', 'jiǎo', 'bù', 'qùn'], 'qùn')
(29572, '石子儿', ['shí', 'zǐ', 'er'], 'er')
(29809, '碌碡', ['liù', 'zhou'], 'zhou')
(30813, '竿头日上', ['gān', 'tóu', 'rí', 'shàng'], 'rí')
(30850, '笔头儿', ['bǐ', 'tou', 'er'], 'er')
(30867, '符号逻辑', ['fú', 'hào', 'luó', 'ji'], 'ji')
(31042, '簸箕', ['bò', 'ji'], 'ji')
(31169, '糠豆不赡', ['kang', 'dou', 'bu', 'shan'], 'kang')
(31169, '糠豆不赡', ['kang', 'dou', 'bu', 'shan'], 'dou')
(31169, '糠豆不赡', ['kang', 'dou', 'bu', 'shan'], 'bu')
(31169, '糠豆不赡', ['kang', 'dou', 'bu', 'shan'], 'shan')
(31376, '红澄澄', ['hóng', 'deng', 'deng'], 'deng')
(31376, '红澄澄', ['hóng', 'deng', 'deng'], 'deng')
(31866, '绳愆纠缪', ['sheng', 'qian', 'jiu', 'miu'], 'sheng')
(31866, '绳愆纠缪', ['sheng', 'qian', 'jiu', 'miu'], 'miu')
(31953, '缝儿', ['fèng', 'er'], 'er')
(32262, '老头儿', ['lǎo', 'tou', 'er'], 'er')
(33342, '芫荽', ['yán', 'sui'], 'sui')
(33441, '苤蓝', ['piě', 'lan'], 'lan')
(33796, '落魄不偶', ['luo', 'tuo', 'bu', 'ou'], 'tuo')
(33796, '落魄不偶', ['luo', 'tuo', 'bu', 'ou'], 'bu')
(33846, '蒙着锅儿', ['mēng', 'zhe', 'guō', 'er'], 'er')
(33936, '薄荷', ['bò', 'he'], 'he')
(33937, '薄荷脑', ['bò', 'he', 'nǎo'], 'he')
(34779, '裂裳衣疮', ['liè', 'sháng', 'yī', 'chuāng'], 'sháng')
(35776, '话把儿', ['huà', 'bà', 'er'], 'er')
(35931, '说头儿', ['shuō', 'tou', 'er'], 'er')
(36149, '谄上抑下', ['chǎn', 'shàng', 'yi', 'xià'], 'yi')
(36434, '货而不售', ['huo', 'er', 'bu', 'shou'], 'er')
(36434, '货而不售', ['huo', 'er', 'bu', 'shou'], 'bu')
(36728, '赶活儿', ['gǎn', 'huó', 'er'], 'er')
(36812, '趔趄', ['liè', 'qie'], 'qie')
(37837, '这么点儿', ['zhè', 'me', 'diǎn', 'er'], 'er')
(37840, '这会儿', ['zhè', 'huì', 'er'], 'er')
(38086, '迷迷糊糊', ['mí', 'mi', 'hū', 'hū'], 'mi')
(38680, '那么点儿', ['nà', 'me', 'diǎn', 'er'], 'er')
(38683, '那会儿', ['nà', 'huì', 'er'], 'er')
(38724, '邯郸重步', ['hán', 'dān', 'zhóng', 'bù'], 'zhóng')
(38771, '都督', ['dū', 'du'], 'du')
(38859, '醋劲儿', ['cù', 'jìn', 'er'], 'er')
(39293, '钉头磷磷', ['ding', 'tou', 'lin', 'lin'], 'ding')
(39293, '钉头磷磷', ['ding', 'tou', 'lin', 'lin'], 'lin')
(39293, '钉头磷磷', ['ding', 'tou', 'lin', 'lin'], 'lin')
(39369, '钢镚儿', ['gāng', 'bèng', 'er'], 'er')
(39510, '铆劲儿', ['mǎo', 'jìn', 'er'], 'er')
(40066, '闷头儿', ['mèn', 'tou', 'er'], 'er')
(40067, '闷头儿干', ['mēn', 'tóu', 'er', 'gàn'], 'er')
(40068, '闷头儿干活', ['mēn', 'tóu', 'er', 'gàn', 'huó'], 'er')
(40089, '闹嚷嚷', ['nào', 'rāng', 'rang'], 'rang')
(40212, '阿Q', ['ā', 'Q'], 'Q')
(40453, '隐占身体', ['yin', 'zhan', 'shen', 'qi'], 'zhan')
(40453, '隐占身体', ['yin', 'zhan', 'shen', 'qi'], 'shen')
(40562, '难进易退', ['nan', 'jin', 'yi', 'tui'], 'nan')
(40562, '难进易退', ['nan', 'jin', 'yi', 'tui'], 'jin')
(40562, '难进易退', ['nan', 'jin', 'yi', 'tui'], 'yi')
(40562, '难进易退', ['nan', 'jin', 'yi', 'tui'], 'tui')
(40986, '面片儿', ['miàn', 'piān', 'er'], 'er')
(41579, '飞将数奇', ['fē', 'jiàng', 'shù', 'jī'], 'fē')
(41639, '食不重肉', ['shí', 'bù', 'zhóng', 'ròu'], 'zhóng')
(41819, '馄饨', ['hún', 'tun'], 'tun')
(41820, '馄饨皮儿', ['hún', 'tun', 'pí', 'er'], 'tun')
(41820, '馄饨皮儿', ['hún', 'tun', 'pí', 'er'], 'er')
(41851, '香培玉琢', ['xiang', 'pei', 'yu', 'zuo'], 'xiang')
(41851, '香培玉琢', ['xiang', 'pei', 'yu', 'zuo'], 'pei')
(42080, '骨朵儿', ['gū', 'duǒ', 'er'], 'er')
(42278, '鬼怕恶人', ['guǐ', 'pà', 'èr', 'én'], 'én')
(42767, '鼎鼐调和', ['dǐng', 'nai', 'tiáo', 'hé'], 'nai')
(42912, '龙游曲沼', ['long', 'you', 'qu', 'zhao'], 'long')

拼音，数量
er 85
ji 8
yi 5
béi 1
nai 4
wé 1
bu 5
xi 3
dong 1
hou 1
gui 1
mao 1
tan 1
tun 3
sheng 7
dao 2
he 3
pai 3
wo 1
chao 2
sang 2
pen 1
rang 2
jíng 1
tian 1
bao 1
nian 1
m 1
kuàn 1
chuo 1
di 1
zhong 2
shuo 1
zhu 1
zhai 1
lü 2
zu 1
dan 1
jān 1
mei 1
fē 2
shu 1
hei 1
kou 1
zeng 1
chan 1
ran 1
yue 1
nu 1
cheng 1
ren 1
xiang 2
ying 1
qùn 1
zhou 1
rí 1
kang 1
dou 1
shan 1
deng 2
miu 1
sui 1
lan 1
tuo 1
sháng 1
qie 1
mi 1
zhóng 2
du 1
ding 1
lin 2
Q 1
zhan 1
shen 1
nan 1
jin 1
tui 1
pei 1
én 1
long 1

**Comment by linzehua** [comment]
在phrase-pinyin-data/large_pinyin.txt则更多

er 745
ge 38
fen 3
ji 57
bu 84
lai 14
yi 22
béi 1
nai 17
xi 33
ceng 1
xiang 7
wé 2
dong 4
huan 7
dan 16
wan 1
an 3
tun 9
jin 4
wo 5
nu 2
jiǔì 1
xia 10
rang 5
mu 3
cai 6
ci 1
báng 1
hou 10
he 14
ai 2
kan 4
liao 1
chan 2
ran 4
zheng 2
she 4
zhai 4
shuo 3
mei 6
sheng 27
gui 5
mao 6
dou 2
ren 13
dao 16
guēn 1
cheng 5
nei 1
wang 7
nao 4
qie 3
gang 3
d 2
tan 5
zhu 7
hua 6
lue 1
tong 7
bi 4
jǜ 2
shu 8
làun 1
hao 2
kou 4
tao 17
pai 5
tang 5
chao 4
xun 2
song 1
nong 3
yue 3
sang 4
ku 1
 1
gua 2
cha 1
en 1
pen 2
chong 2
lun 3
keng 1
die 3
jíng 1
tian 1
bao 3
nian 2
gao 2
sh 4
zhng 2
m 1
kuàn 1
feng 4
mi 9
niu 1
niang 7
nen 1
shen 4
zhuang 3
sao 1
xuá 2
zai 7
chuo 1
di 3
ga 2
cang 2
cun 1
pi 1
shan 3
yao 3
peng 2
bang 1
zh 2
fei 2
gan 1
zhuan 1
hong 1
yuan 1
ruo 4
guan 1
zhong 3
fan 7
du 2
mang 4
jun 1
ben 1
lü 2
man 3
que 1
teng 4
ha 1
nie 1
zu 1
chou 3
che 3
jān 1
cuo 1
lian 2
ying 10
fē 2
hei 1
rū 1
leng 2
duan 2
heng 2
deng 8
tuo 4
geng 2
zeng 1
zhui 3
bǒi 1
mian 2
kuai 2
pa 3
yèn 1
chuan 1
yǘ 1
zái 1
pao 1
sui 3
xou 1
ang 1
tātuī 1
zhou 5
bing 3
dúu 1
bòo 1
yan 5
déng 1
za 2
nan 3
pan 1
qùn 1
liu 4
long 3
rí 1
kang 1
jue 1
miu 1
qin 1
guai 1
shao 1
lan 1
xóng 1
gou 1
zao 1
ding 2
sháng 1
xie 1
èer 1
kai 2
gūi 1
dè 1
tui 2
fuǐ 1
kéng 1
zhóng 2
zhen 1
lin 2
yiě 1
Q 1
jǖ 1
qiu 1
zhan 1
j 1
miān 1
pei 1
én 1

**Comment by mozillazg** [comment]
@linzehua 感谢反馈！phrase-pinyin-data/pinyin.txt 中的部分拼音确实有误（er 那个轻声是预期的），我抽空再整理一下。同时也欢迎给 https://github.com/mozillazg/phrase-pinyin-data 提交 PR 😄
