### ISSUE TITLE
获取韵母时，把韵母部分 ‘ia' / ’iao‘ 识别成了一个整体,无法区分开来

### ISSUE THREAD

**Issue by shedegege** [mozillazg/python-pinyin#177]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：3.6.7
* pypinyin 版本：0.35.3

## 问题描述
比如汉字 ’下‘，它的韵母应该是 ['i', 'a'], 现在识别成了['ia']，
比如汉字 ’跳‘，它的韵母应该是 ['i', 'ao'], 现在识别成了['iao']，

## 问题复现步骤
>>> pypinyin.pinyin("下", style=5, heteronym=True, strict=True)
[['ia']]

>>> pypinyin.pinyin("跳", style=5, heteronym=True, strict=True)
[['iao', 'ao']]

**Comment by mozillazg** [comment]
@shedegege 嗯，不过其实 `ia` 和 `iao` 就是正确的韵母，结果是符合预期的，详见 [《汉语拼音方案》](http://www.moe.edu.cn/s78/A19/yxs_left/moe_810/s230/195802/t19580201_186000.html) 

<img width="561" alt="image" src="https://user-images.githubusercontent.com/485054/58711258-bc891180-83f0-11e9-9462-0e8aca8c0f4c.png">
