### ISSUE TITLE
想问一下目前是否支持按音素切分？

### ISSUE THREAD

**Issue by sailist** [mozillazg/python-pinyin#180]

**Comment by sailist** [comment]
看到作者说添加了新特性，但是我下的代码里貌似不可用，是库没有更新的问题吗^_^

**Comment by mozillazg** [comment]
目前不支持。

**Comment by sailist** [comment]
好的，谢谢，不知道朋友你知道有哪些可以对拼音切分音素的库吗

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by mozillazg** [comment]
不好意思，我没关注音素方面的知识，所以不清楚有哪些库支持这个。

**Comment by sailist** [comment]
恩恩，好的，谢谢啦

获取 Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by KAIMAN0** [comment]
请问有拼音库吗?

**Comment by mozillazg** [comment]
@KAIMAN0 没明白你说的【拼音库】指的是啥？
