### ISSUE TITLE
“谁”发音不准确

### ISSUE THREAD

**Issue by nonva** [mozillazg/python-pinyin#181]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：2.7.5
* pypinyin 版本：0.330

## 问题描述
pinyin('谁'.decode('utf-8')')
输出为 shei，没有这种发音
正确的应该是 shui

**Comment by mozillazg** [comment]
有两个音，shei 和 shui 都可以：

<img width="523" alt="image" src="https://user-images.githubusercontent.com/485054/61167583-f31b8580-a573-11e9-82b5-1acd8df6b69c.png">

http://www.guoxuedashi.com/kangxi/pic.php?f=xdhycd&p=1150

具体细节和争论可以在搜索引擎中搜索一下 谁的发音。
