### ISSUE TITLE
“积蓄”拼音错误

### ISSUE THREAD

**Issue by nonva** [mozillazg/python-pinyin#182]
## 运行环境

* 操作系统（Linux/macOS/Windows）：linux
* Python 版本： 2.75
* pypinyin 版本：0.330

## 问题描述

“积蓄”拼音输出是“ji chu”， 应该是“ji xu”

**Comment by mozillazg** [comment]
感谢反馈！

**Comment by nonva** [comment]
豆豉 拼音输出 dou shi； 应该为 dou chi
