### ISSUE TITLE
关于u -> v的转换问题，我该如何如何调整

### ISSUE THREAD

**Issue by zcmiao190** [mozillazg/python-pinyin#186]
## 运行环境

* 操作系统（Linux/macOS/Windows）：win10
* Python 版本：3.7
* pypinyin 版本：  '__version__': '0.35.4',

## 问题描述

u -> v的转换问题， `strict`选项似乎无效？

## 问题复现步骤
```
In [14]: from pypinyin import pinyin, lazy_pinyin, Style

In [15]: lazy_pinyin("战略")
Out[15]: ['zhan', 'lve']

In [16]: pinyin("战略")
Out[16]: [['zhàn'], ['lüè']]

```

现在我想得到zhan lue的输出
应该如何做调整？

**Comment by mozillazg** [comment]
没有提供对应的选项，需要自行对返回的结果做二次处理。

**Comment by mozillazg** [comment]
最新版增加了一个实现这个需求的辅助方法：https://pypinyin.readthedocs.io/zh_CN/master/contrib.html#v2umixin
