### ISSUE TITLE
“存储”拼音错误

### ISSUE THREAD

**Issue by bmxbmx3** [mozillazg/python-pinyin#187]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Windows
* Python 版本：3.7.1
* pypinyin 版本：0.35.4

## 问题描述
“储”字只有一个读音chu3，但是用pypinyin转换“存储”这个词时，出现“cun2 chu2”这个读音，其中chu2不正确，但对“储蓄”这个词转换读音为“chu3 xu4”，这是chu3发音正确。

[存储发音](https://cidian.911cha.com/MTRidmk=.html)

## 问题复现步骤
运行以下代码
```
print(pypinyin.pinyin("储蓄", heteronym=False, style=Style.TONE3))
```
出现
```
[['chu3'], ['xu4']]
```
正确。

但运行
```
print(pypinyin.pinyin("存储", heteronym=False, style=Style.TONE3))
```
出现
```
[['cun2'], ['chu2']]
```
错误。

**Comment by mozillazg** [comment]
@bmxbmx3 感谢反馈！
