### ISSUE TITLE
单字中无轻声，单词中出现轻声

### ISSUE THREAD

**Issue by wizardk** [mozillazg/python-pinyin#191]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：3.7
* pypinyin 版本：0.36.0

## 问题描述
'弟'在单字中有di4/ti4/tui2三个音，并没有轻声，而'弟弟'的拼音为'di4 di'，出现了轻声

## 问题复现步骤
```
from pypinyin import pinyin, Style
print(pinyin('弟', style=Style.TONE3, heteronym=True))  # [['di4', 'ti4', 'tui2']]
print(pinyin('弟弟', style=Style.TONE3, heteronym=False))  # [['di4'], ['di']]
```

**Comment by mozillazg** [comment]
感谢反馈，待我有空的时候研究一下轻声究竟算不算一个字的读音。

**Comment by JohnHerry** [comment]
加入轻声应该是考虑了 口读的特点。 这些查新华字典是没用的。字典没有这个拼音但是有些场景读的时候就应该读轻声。
