### ISSUE TITLE
拼音和其他项组合排序会报错

### ISSUE THREAD

**Issue by JANPCOE** [mozillazg/python-pinyin#192]
## 运行环境

* 操作系统（Linux/macOS/Windows）：win 7 x64
* Python 版本：3.7.5
* pypinyin 版本： 0.36.0

## 问题描述
单独用拼音或者其他项排序没有问题，如果拼音一样，再按其他列排序会报错。

## 问题复现步骤
```
import pandas as pd
import pypinyin
from pypinyin import lazy_pinyin

df= {'id':[1,2,3,4,5,6],'name':['张山','李四','王二麻子','李五','王六','张三 '],'math':[90,89,99,78,97,93],'english':[89,94,80,94,94,90]}
df = pd.DataFrame(df)
print(df)
# 生成一张表
df['pinyin']= df.apply(lambda x :  lazy_pinyin(x['name']), axis=1)
print(df.sort_values('pinyin'))
# 按拼音排序ok
print(df.sort_values('math'))
# 按成绩排序ok
print(df.sort_values(by=['english','math']))
# 按两项成绩排序ok
print(df.sort_values(by=['pinyin','math']))  
# 按拼音和成绩排序fail
```

**Comment by mozillazg** [comment]
感谢反馈，待我有空的时候看一下。

**Comment by shinecurve** [comment]
我也遇到了这个问题，好像是pandas的问题？
lazy_pinyin() 返回的是一个列表，处理下这个列表可以解决排序的问题...
df['pinyin'] = df.apply(lambda x: ''.join(lazy_pinyin(x['name'])), axis=1)

**Comment by mozillazg** [comment]
> 我也遇到了这个问题，好像是pandas的问题？
> lazy_pinyin() 返回的是一个列表，处理下这个列表可以解决排序的问题...
> df['pinyin'] = df.apply(lambda x: ''.join(lazy_pinyin(x['name'])), axis=1)

@shinecurve 感谢分享
