### ISSUE TITLE
注音錯誤

### ISSUE THREAD

**Issue by WhymustIhaveaname** [mozillazg/python-pinyin#193]
* 操作系统：ubuntu16.04
* Python 版本：3.5.2
* pypinyin 版本：0.36.0
pypinyin.pinyin(str,style=pypinyin.Style.TONE3)

**Comment by WhymustIhaveaname** [comment]
pypinyin.pinyin("漸染, 漸漬, 漸澤, 漸仁摩誼",style=pypinyin.Style.TONE3)
[['jian4'], ['ran3'], [', '], ['jian4'], ['zi4'], [', '], ['jian4'], ['ze2'], [', '], ['jian4'], ['ren2'], ['mo2'], ['yi4']]
然而所有漸都應該念一聲

**Comment by WhymustIhaveaname** [comment]
揭衣涉水 程序显示念 jie1 然而应该念 qi4

**Comment by WhymustIhaveaname** [comment]
pypinyin.pinyin("荸薺",style=pypinyin.Style.TONE3)
[['bi2'], ['ji4']]
然而实际是 bi2 qi(轻声)，但改为简体后就好了

**Comment by WhymustIhaveaname** [comment]
pypinyin.pinyin("夜如何其, 酈食其",style=pypinyin.Style.TONE3)
[['ye4'], ['ru2'], ['he2'], ['qi2'], [', '], ['li4'], ['shi2'], ['qi2']]
此后简单词一概不注正确音

**Comment by WhymustIhaveaname** [comment]
pypinyin.pinyin("倔強",style=pypinyin.Style.TONE3)
[['jue2'], ['qiang2']]

**Comment by WhymustIhaveaname** [comment]
pypinyin.pinyin("強求, 勉強, 強顏歡笑, 強迫",style=pypinyin.Style.TONE3)
[['qiang2'], ['qiu2'], [', '], ['mian3'], ['qiang2'], [', '], ['qiang2'], ['yan2'], ['huan1'], ['xiao4'], [', '], ['qiang2'], ['po4']]

**Comment by WhymustIhaveaname** [comment]
pypinyin.pinyin("親家",style=pypinyin.Style.TONE3)
[['qin1'], ['jia1']]

**Comment by WhymustIhaveaname** [comment]
pypinyin.pinyin("呼天搶地, 搶風, 搶水",style=pypinyin.Style.TONE3)
[['hu1'], ['tian1'], ['qiang3'], ['de'], [', '], ['qiang3'], ['feng1'], [', '], ['qiang3'], ['shui3']]

**Comment by WhymustIhaveaname** [comment]
pypinyin.pinyin("鞭鞘",style=pypinyin.Style.TONE3)
[['bian1'], ['qiao4']]

**Comment by WhymustIhaveaname** [comment]
pypinyin.pinyin("謦欬",style=pypinyin.Style.TONE3)
[['qing4'], ['kai4']]

**Comment by mozillazg** [comment]
感谢反馈，我有空的时候看一下。

**Comment by mozillazg** [comment]
已调整拼音，部分繁体词语需要转换为简体
