### ISSUE TITLE
单字的多音情况太多了，只想用其中某一个字库，可以吗？

### ISSUE THREAD

**Issue by sorrytaobao** [mozillazg/python-pinyin#198]
直接安装之后，发现某些字的多音读音很多，比如“扔”字，默认的多音是[['rēng', 'rèng']]
其中rèng大部分情况是不需要的，所以有没有办法指定pinyin-data中的某一个库？
比如，只用kXHC1983.txt

**Comment by mozillazg** [comment]
不支持这个功能，不过你可以通过下面的方法间接实现：

1. 使用 `kXHC1983.txt` 生成一个新的拼音数据文件：

```
$ python gen_pinyin_dict.py pinyin-data/kXHC1983.txt new_pinyin_data.py
```
2. 使用这个新的拼音数据覆盖已有的数据（文档：https://pypinyin.readthedocs.io/zh_CN/master/usage.html#custom-dict ）:

```
>>> from pypinyin import load_single_dict, pinyin
>>> import new_pinyin_data
>>> load_single_dict(new_pinyin_data.pinyin_dict)
>>> pinyin(u'扔')
```

**Comment by sorrytaobao** [comment]
非常感谢，我试试

**Comment by sorrytaobao** [comment]
Traceback (most recent call last):
  File "G:/gitIdeaProjects/python-pinyin/gen_pinyin_dict.py", line 38, in <module>
    main(in_fp, out_fp)
  File "G:/gitIdeaProjects/python-pinyin/gen_pinyin_dict.py", line 12, in main
    for line in in_fp.readlines():
UnicodeDecodeError: 'gbk' codec can't decode byte 0x87 in position 19: illegal multibyte sequence
字符编码有问题了？

**Comment by sorrytaobao** [comment]
我在代码里input的open里了编码就可以了

**Comment by sorrytaobao** [comment]
另外还有个问题麻烦一下，我想自己修改字库，但是又不想在代码里硬编，是否可以通过方法直接修改pinyin-data里的字库？我看Pinyin-data里的字库有好多个，也有纠正的字库，这个多个字库怎么用？是将所有的字库，都通过上面的方法生成一个文件吗？

**Comment by mozillazg** [comment]
可以看一下 https://github.com/mozillazg/pinyin-data/blob/master/merge_unihan.py 这个程序, pinyin.txt 就是用这个程序生成的。

**Comment by mozillazg** [comment]
> 直接安装之后，发现某些字的多音读音很多，比如“扔”字，默认的多音是[['rēng', 'rèng']]
> 其中rèng大部分情况是不需要的，所以有没有办法指定pinyin-data中的某一个库？
> 比如，只用kXHC1983.txt

新开发了一个项目 [pypinyin-dict ](https://github.com/mozillazg/pypinyin-dict) 提供了一个预置的方法来实现这个需求：

```bash
$ pip install pypinyin-dict
```

```python
>>> from pypinyin import pinyin
>>> pinyin('扔', heteronym=True)
[['rēng', 'rèng']]
>>> from pypinyin_dict.pinyin_data import kxhc1983
>>> kxhc1983.load()
>>> pinyin('扔', heteronym=True)
[['rēng']]
>>>
```

具体介绍详见项目仓库 README
