### ISSUE TITLE
testing of load_phrases_dict

### ISSUE THREAD

**Issue by jeremy886** [mozillazg/python-pinyin#20]
load_phrases_dict({'几': [['jǐ']]})
load_phrases_dict({'桔子': [['jú'], ['zǐ']]})
load_phrases_dict({'还没': [['hái'], ['méi']]})
load_phrases_dict({'不用谢':[['bú'], ['yòng'],['xiè']]})

Output
不用谢(bú yòng xiè)
桔子(jú zǐ)
还没(huán méi)
几(jǐ)

#####
So 还没 is incorrect. Why?

**Comment by mozillazg** [comment]
经试验后发现是分词的原因，`jieba` 分词后的结果是 `还没` 被拆分成了 `还` 和 `没`，所以词组拼音没有被应用。两种解决办法:

1. 使用字符串列表作为参数，手动分词:

```python
>>> pinyin('还没')
[['huán'], ['méi']]
>>> pinyin(['还没'])
[['hái'], ['méi']]
```
2. 卸载或禁用 ``jieba`` 分词，最新版的 pypinyin 已内置简单的分词功能. 详见文档 [1] [2]

[1] http://pypinyin.readthedocs.org/en/master/#tips
[2] http://pypinyin.readthedocs.org/en/master/#id11

**Comment by jeremy886** [comment]
谢谢解答，我大概看了一下结巴分词，把"还没"加到jieba/dict.txt，再把"还没"的拼音加到pypinyin/phrase_dict.py，之后拼音就正确了。

jieba/dict.txt
还没 300 d

pypinyin/phrase_dict.py
    '还没': [['hái'], ['méi']],

结果：
========
我作业还没写完。	wǒ zuò yè hái méi xiě wán 。

**Comment by mozillazg** [comment]
@jeremy886 :+1:
