### ISSUE TITLE
疑问, 会不会出现词典外的中文字符导致无法转换?

### ISSUE THREAD

**Issue by terryyizhong** [mozillazg/python-pinyin#200]
如果有词典外的中文字符, pypinyin转换会如何处理? 直接略过吗

**Comment by mozillazg** [comment]
@terryyizhong 可以控制的，具体可以看一下这个场景对应的文档：https://pypinyin.readthedocs.io/zh_CN/master/usage.html#handle-no-pinyin

**Comment by terryyizhong** [comment]
谢谢解答
