### ISSUE TITLE
对省略号的处理不符合常规

### ISSUE THREAD

**Issue by gezimonkey** [mozillazg/python-pinyin#201]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：3.6
* pypinyin 版本：0.36.0

## 问题描述
对文本进行切片时发现切片长度和pypinyin转换完的长度不匹配;
最终发现是省略号的问题
python处理省略号是两个…
而pypinyin是......

**Comment by gezimonkey** [comment]
还有？——如果连续
会识别为？——
而不是？和——

**Comment by mozillazg** [comment]
感谢反馈~

但是，两个… 不就是 ...... 嘛😂  猜测你在说分词的问题？如果是这个问题的话，有两个解决办法：
* 你先按照你的方法对字符串做分词，然后再传入到 pypinyin ，文档： https://pypinyin.readthedocs.io/zh_CN/master/api.html#pypinyin.pinyin
* 按处理没有拼音字符的方法来处理，可以看一下对应的自定义处理方式的文档（对于你说的这个问题你可以自定义一个对没有拼音的字符串做二次分词的函数）：https://pypinyin.readthedocs.io/zh_CN/master/usage.html#handle-no-pinyin
