### ISSUE TITLE
小问题

### ISSUE THREAD

**Issue by asaketsu** [mozillazg/python-pinyin#202]
## 运行环境

* 操作系统（Linux/macOS/Windows）：w
* Python 版本：3.8.2
* pypinyin 版本：37

## 问题描述
1、省略号、破折号处理有问题，用-号替换好了
2、注音对齐处理效果不是很好
3、注到一半就断，看了是记数问题
感谢！已经很好！

**Comment by mozillazg** [comment]
感谢反馈~

* 关于省略号和破折号的问题可以看一下这个 https://github.com/mozillazg/python-pinyin/issues/201 

> 2、注音对齐处理效果不是很好
> 3、注到一半就断，看了是记数问题

不知道是否方便具体说一下这个注音的问题，如果能提供具体示例就更好了，谢谢~

**Comment by asaketsu** [comment]
2、注音对齐问题，可能原版phoneticguide就没有处理好，再加宽字间距后，拼音和字上下对齐是个问题，cneter和left均会微小偏离；
3、程序分2个step，在step 1 时统计的count数，其实含有很多空值或符号占位等，于是在step 2 时只处理到step 1 中的count 就停止，其实没有完，重新选余下的就可以继续处理，但这是一个循环，一次比一次少，重复选余文，直到最后一个字，也能处理完。
