### ISSUE TITLE
“还珠格格”的注音结果为 hái zhū gé gé 希望修复

### ISSUE THREAD

**Issue by fkxxyz** [mozillazg/python-pinyin#204]
## 运行环境

* 操作系统（Linux/macOS/Windows）： archlinux
* Python 版本： 3.8.3
* pypinyin 版本：  0.37.0

## 问题描述
“还珠格格”的注音结果为 hái zhū gé gé 希望修复。

## 问题复现步骤
```python
import pypinyin            
pypinyin.pinyin('还珠格格')
```

**Comment by mozillazg** [comment]
@fkxxyz 感谢反馈。着急的话，可以通过 https://github.com/mozillazg/python-pinyin#id5 这里的方法临时 workaround 一下。
