### ISSUE TITLE
“??银行”和“??行业”这二大类词语解读错误

### ISSUE THREAD

**Issue by processor2018** [mozillazg/python-pinyin#205]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Windows 10
* Python 版本：3.7
* pypinyin 版本：0.38.0

## 问题描述
“银行”和“行业”单独的二个词无问题，但和其它字或词语组合在一起后，解读错误。

## 问题复现步骤

assert pinyin("金融行业", Style.FIRST_LETTER)[2] == ['h']
assert pinyin("军工行业", Style.FIRST_LETTER)[2] == ['h']
assert pinyin("浦发银行", Style.FIRST_LETTER)[3] == ['h']
assert pinyin("交通银行", Style.FIRST_LETTER)[3] == ['h']

**Comment by mozillazg** [comment]
@processor2018 感谢反馈，我看一下。
