### ISSUE TITLE
勺 dì的读音我没查到

### ISSUE THREAD

**Issue by zhaoyi126** [mozillazg/python-pinyin#207]
python 3.5.3

import pypinyin
[i for i in pypinyin.pinyin(word, heteronym=True, strict=True)]

勺 
[['sháo', 'shuò', 'zhuó', 'dì']]
dì的读音我没查到.

吞
[['tūn', 'tiān']]
tiān的读音我没查到.

**Comment by mozillazg** [comment]
@zhaoyi126 

勺 dì: http://www.ivantsoi.com/hydzd/orgpage.html?page=282
吞 tiān: http://www.ivantsoi.com/hydzd/orgpage.html?page=634

具体使用的数据源详见 https://github.com/mozillazg/python-pinyin#%E6%8B%BC%E9%9F%B3%E6%95%B0%E6%8D%AE
