### ISSUE TITLE
建议："白干"这个词语在软件自带字典中的注音

### ISSUE THREAD

**Issue by processor2018** [mozillazg/python-pinyin#208]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Windows 10
* Python 版本：3.7
* pypinyin 版本：0.38.1

## 问题描述
软件自带词典phrases_dict.py中对“白干”的注音一共有三个
'白干': [['bái'], ['qián']],
'白干儿': [['bái'], ['gān'], ['ér']],
'老白干儿': [['lǎo'], ['bái'], ['gān'], ['ér']],

对于第一个词'白干': [['bái'], ['qián']],
没有明白这个注音的来源，是新出现的网络词汇、还是专有人名？请指教。
已了解的中文意义大致有如下几个，遗漏的请指教
（1）[['bái'], ['gàn']]，“一天白干”、“白干活了”
没有效果的工作
（2）[['bái'], ['gàn']]，“白干活不给钱”
免费、无偿的劳动，
（3）[['bái'], ['gān']],
河北方言，白酒，phrases_dict中的后二个词“老白干儿”，“白干儿”，即此意

## 问题复现步骤
assert pinyin("一天白干") == [['yī'], ['tiān'], ['bái'], ['gàn']]
#### 这个注音，是否还和分词策略有关？“干活”在内置词典phrases_dict.py中是正确的注音
assert pinyin("白干活") == [['bái'], ['gàn'], ['huó']]
#### 这个放宽一些，至少能标成gan的音
assert  (pinyin("老白干酒") == [['lǎo'], ['bái'], ['gān'], ['jiǔ']])  |  (pinyin("老白干酒") == [['lǎo'], ['bái'], ['gàn'], ['jiǔ']])

**Comment by mozillazg** [comment]
@processor2018 感谢反馈。`'白干': [['bái'], ['qián']]` 这个数据应该是有问题我后面删除一下。着急的话可以通过下面的方法 workaround 一下：

```
In [1]: from pypinyin import pinyin

In [2]: pinyin("一天白干")
Out[2]: [['yī'], ['tiān'], ['bái'], ['qián']]

In [3]: from pypinyin import load_phrases_dict

In [4]: load_phrases_dict({'白干': [['bái'], ['gàn']]})

In [5]: pinyin("一天白干")
Out[5]: [['yī'], ['tiān'], ['bái'], ['gàn']]

In [6]: pinyin("白干活")
Out[6]: [['bái'], ['gàn'], ['huó']]

In [7]: pinyin("老白干酒")
Out[7]: [['lǎo'], ['bái'], ['gàn'], ['jiǔ']]

```

**Comment by mozillazg** [comment]
最新版已修改
