### ISSUE TITLE
strict参数对韵母的影响

### ISSUE THREAD

**Issue by gongel** [mozillazg/python-pinyin#210]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Windows
* Python 版本：3.7.6
* pypinyin 版本：0.38.1

## 问题描述

\>>> pinyin("睡觉", style=5, heteronym=False, strict=True)
[['uei'], ['iao']]

\>>> pinyin("睡觉", style=5, heteronym=False, strict=False)
[['ui'], ['iao']]

“觉”的strict=False版本的韵母应该为'ao'?

谢谢。

**Comment by mozillazg** [comment]
> “觉”的strict=False版本的韵母应该为'ao'?

不是，jiao 这个拼音不是特殊拼音，它的韵母就是 `iao`

shui 这个拼音是因为命中了《汉语拼音方案》里下面的规则，所以才会不一样：

> iou，uei，uen前面加声母的时候，写成iu，ui，un。例如niu(牛)，gui(归)，lun(论)。 （韵母相关风格下还原正确的韵母 iou，uei，uen）

详见：https://pypinyin.readthedocs.io/zh_CN/master/usage.html#strict

**Comment by gongel** [comment]
ok
