### ISSUE TITLE
一些值得改进的小问题

### ISSUE THREAD

**Issue by dreamermary** [mozillazg/python-pinyin#218]
## 问题描述
* en无声母时，strict生成的拼音为n。这个是不是错的？eg，`ym = pinyin('嗯', strict=True, style=Style.FINALS_TONE3) ` `ym->n`
* FINALS_TONE3风格下，strict=True参数不起作用(strict下y和w不作声母)。eg，`mpy = pinyin('一', style=Style.TONE3, strict=True)` `mpy->yi`

**Comment by mozillazg** [comment]
@dreamermary 

* 嗯 没错，参考这个 https://github.com/mozillazg/python-pinyin/issues/109
* strict 参数只在只获取声母或只获取韵母的风格下生效，TONE3 符合预期，FINALS_TONE3 也符合预期因为 y 和 w 既不是声母也不是韵母，详见 汉语拼音方案 http://www.moe.gov.cn/s78/A19/yxs_left/moe_810/s230/195802/t19580201_186000.html
