### ISSUE TITLE
对于“地”的多音处理

### ISSUE THREAD

**Issue by R0uter** [mozillazg/python-pinyin#220]
地 这个字有两个音 di， 和 de，但一般常用为 di，跟在动词后可为de，比如 “蹦蹦跳跳地”

pypinyin 对它的多音字是有处理的，但由于是基于词库，那么就导致必然会有一些词未命中从而处理错误，比如“安地斯山脉”被处理成了“an'de'si'shan'mai”，注意 “地”被翻译成了“de”而不是“di”。

通常，我们习惯“de”音的缺失，比如打字时“欢快地”这个词，如果打“huan'kuai'de”不存在，我们会尝试“huan'kuai'di”，而不是反之……

我们是否需要讨论一下，在没有词库命中的情况下，“地”这个字应该默认取“di”还是“de”拼音？

**Comment by mozillazg** [comment]
有道理，【地】的默认拼音可以改为 `di`。

**Comment by R0uter** [comment]
其实很多词比如 “地球”，“甘地”，“地图”等在语句中很多都被识别成了“de”，变成了 “de qiu” "gan de" "de tu"这样……😅

**Comment by mozillazg** [comment]
> 【地】的默认拼音可以改为 di

最新版已修改。
