### ISSUE TITLE
某些时候会出现错误的韵母如'oon','ion','aun'

### ISSUE THREAD

**Issue by tangkk** [mozillazg/python-pinyin#223]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：
* pypinyin 版本：

## 问题描述
使用jieba里面dict.txt.big，逐行取中文词，进行lazypinyin的转换，有极少时候会出现如题的韵母
'oon','ion','aun'
实际上'oon'对应的是‘ong’，‘aun’对应是‘uan’，‘ion’对应是‘iang’。是个很奇怪的错误。dict.txt.big里面的中文字本身是对的。

**Comment by mozillazg** [comment]
感谢反馈！请问是否方便帮忙提供一下对应的汉字，谢谢~

**Comment by tangkk** [comment]
昨天用最新版的pypinyin重跑了一次好像没有复现问题了。我大概记得aun对应是“栾”或者“峦”字，ion对应是一个“强”字，其他不记得了。是整个词取lazypinyin的时候出现的，绝大部分包含上述字的词转出来是对的，可能对应每个字只有一个词是不对。
