### ISSUE TITLE
有些常用词比如：枯萎  [['kū'], ['wēi']] 错误

### ISSUE THREAD

**Issue by wac81** [mozillazg/python-pinyin#224]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：3.6
* pypinyin 版本：40

类似这样的常用词错误：枯萎  [['kū'], ['wēi']] 不在pinyin.txt 字典里，但是在 large_pinyin.txt字典里，如何自定义加载large字典？

**Comment by mozillazg** [comment]
> 但是在 large_pinyin.txt字典里，如何自定义加载large字典？

可以基于 large_pinyin.txt 生成 phrases_dict，然后再加载:

```
$ python gen_phrases_dict.py phrase-pinyin-data/large_pinyin.txt phrases_dict_large.py

>>> from pypinyin import load_phrases_dict, pinyin
>>> import phrases_dict_large
>>> load_phrases_dict(phrases_dict_large.phrases_dict)
```

**Comment by felixhao28** [comment]
像是 编校 这样的有多音字的词还是会标错。不过这可能就是基于字典表所能达到的极限了吧。再往后估计要上深度学习。

**Comment by mozillazg** [comment]
> ## 运行环境
> 
>     * 操作系统（Linux/macOS/Windows）：
> 
>     * Python 版本：3.6
> 
>     * pypinyin 版本：40
> 
> 
> 类似这样的常用词错误：枯萎 [['kū'], ['wēi']] 不在pinyin.txt 字典里，但是在 large_pinyin.txt字典里，如何自定义加载large字典？
> ## 问题描述
> ## 问题复现步骤


新开发了一个项目 [pypinyin-dict ](https://github.com/mozillazg/pypinyin-dict) 提供了一个预置的方法来实现这个需求：

```bash
$ pip install pypinyin-dict
```

```python
>>> from pypinyin import pinyin
>>> pinyin('枯萎')
[['kū'], ['wēi']]
>>> from pypinyin_dict.phrase_pinyin_data import large_pinyin
>>> large_pinyin.load()
>>> pinyin('枯萎')
[['kū'], ['wěi']]
>>>
```

具体介绍详见项目仓库 README。
