### ISSUE TITLE
请问如何分别得到一个多音字的声母，韵母和音调？（已解决）

### ISSUE THREAD

**Issue by benbijituo** [mozillazg/python-pinyin#225]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：
* pypinyin 版本：

## 问题描述
目前可以通过FINALS_TONE3（heteronym=True）得到中国->``ong1 uo2``
可以通过TONE3（heteronym=True）得到中国->``zhong1 guo2``，看似很容易分离声母韵母声调，但是这个样例太简单了。真实情况是，如果设置heteronym=True，作者会返回一个集合形式的FINALS_TONE3，自动去除重复，它的长度和TONE3是不一致的，例如：
FINALS_TONE3['i2', 'i1', 'i4', 'ai1', 'ian3']     TONE3['qi2', 'ji1', 'ji4', 'zi1', 'zhai1', 'jian3']
FINALS_TONE3['an3', 'an4', 'en4']     TONE3['dan3', 'tan4', 'zhen4', 'shen4']
FINALS_TONE3['ang3', 'eng4']     TONE3['dang3', 'tang3', 'cheng4']
再加上有些拼音没有声母（如wu，yao），简单的循环匹配想要分离也很困难。
请问这个问题真的无解吗？

已经通过
from pypinyin.style._utils import get_initials, get_finals
中的方法解决。建议把这几个函数添加在README中，很有用

**Comment by mozillazg** [comment]
最新版本已经公开了几个用于实现这类拼音转换需求的 [辅助函数](https://pypinyin.readthedocs.io/zh_CN/master/contrib.html#tone-convert)，建议使用文档中最新公开的函数而不是内部函数，内部函数在迭代过程中不会保证兼容性。

```python
>>> from pypinyin.contrib.tone_convert import (
        to_initials, to_finals, to_finals_tone, to_finals_tone2, to_finals_tone3,
        to_normal, to_tone, to_tone2, to_tone3)

>>> to_initials('zhōng')
'zh'
>>> to_finals('zhōng')
'ong'
>>> to_finals_tone('zhōng')
'ōng'
>>> to_finals_tone2('zhōng')
'o1ng'
>>> to_finals_tone3('zhōng')
'ong1'
>>> to_normal('zhōng')
'zhong'
>>> to_tone('zhong1')
'zhōng'
>>> to_tone2('zhōng')
'zho1ng'
>>> to_tone3('zhōng')
'zhong1'
```

更多拼音转换的辅助函数及介绍详见文档：https://pypinyin.readthedocs.io/zh_CN/master/contrib.html#tone-convert
