### ISSUE TITLE
提供几个拼音声调风格转换相关的辅助函数

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/python-pinyin#226]
提供几个拼音声调风格转换相关的辅助函数，实现如下转换：

* `nǐ hǎo` -> `ni hao`
* `nǐ hǎo` -> `ni3 ha3o`
* `ni3 ha3o` -> `nǐ hǎo`
* `ni3 ha3o` -> `ni3 hao3`
* `ni3 ha3o` -> `ni hao`
* `nǐ hǎo` -> `ni3 hao3`
* `ni3 hao3` -> `nǐ hǎo`
* `ni3 hao3` -> `ni3 ha3o`
* `ni3 hao3` -> `ni hao`

**Comment by JohnHerry** [comment]
Well Done！
        再建议增加几个识别不同TONE STYLE拼音的正则表达式，在文本中分离出合法拼音字符串的需求，也是有的。
