### ISSUE TITLE
“帧”字的注音应当是zhen而不是zheng

### ISSUE THREAD

**Issue by fkxxyz** [mozillazg/python-pinyin#227]
## 运行环境

* 操作系统（Linux/macOS/Windows）：linux
* Python 版本：3.9.1
* pypinyin 版本：0.40.0

## 问题描述
“帧”字的注音应当是zhen而不是zheng
详见反馈
- https://github.com/fkxxyz/rime-cloverpinyin/issues/59
- https://github.com/fkxxyz/rime-cloverpinyin/issues/57
我在百度百科上看到也是 zhen

## 问题复现步骤

```python
import pypinyin
pypinyin.pinyin('帧')
```

**Comment by mozillazg** [comment]
@fkxxyz 感谢反馈！这个字似乎是个多音字：

```python
>>> pypinyin.pinyin('帧', heteronym=True)
[['zhèng', 'zhēn']]
```

可能需要调整一下顺序，把 `zhēn` 放到第一位，等我有空的时候调整一下。

**Comment by district10** [comment]
词组表里面有这个词，

<https://github.com/mozillazg/phrase-pinyin-data/blob/22ed9d35cfb5ca5d8dbbea60938becafd9efa238/large_pinyin.txt>

```python
def patch_pinyin_dict():
    phrases = {}
    with open('large_pinyin.txt') as f:
        lines = f.readlines()
        for line in lines:
            cols = line.split(': ')
            if len(cols) != 2:
                continue
            hanzi = cols[0]
            pinyin = cols[1].split()
            if len(hanzi) != len(pinyin):
                print(f'skip line {line}')
                continue
            phrases[hanzi] = [[p] for p in pinyin]
    pypinyin.load_phrases_dict(phrases)
```

文档里没给链接，翻了一下才知道有官方的词汇表。
