### ISSUE TITLE
注音转拼音

### ISSUE THREAD

**Issue by leileilin** [mozillazg/python-pinyin#228]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：
* pypinyin 版本：

## 问题描述
本人想把一些台湾字典的注音转换为拼音，不知道该包是否支持，如果支持的话，能不能给个详细步骤，非常感谢！！

**Comment by mozillazg** [comment]
@leileilin 这个包不支持这个功能。
