### ISSUE TITLE
和诗

### ISSUE THREAD

**Issue by fangqiang817** [mozillazg/python-pinyin#230]
from pypinyin import pinyin

pinyin("成语和诗歌")

output:
[['chéng'], ['yǔ'], ['hè'], ['shī'], ['gē']]

小伙子，咋回事？是不是分词有问题 ～_～

**Comment by mozillazg** [comment]
`和诗` 是一个词语所以会得到这个结果（内置的分词无法处理这种复杂的情况）。
你可以使用其他分词模块先对字符串进行分词然后把分词后的结果列表作为 pinyin 函数的参数：https://pypinyin.readthedocs.io/zh_CN/master/api.html#pypinyin.pinyin

```python
>>> words = ["成语", "和", "诗歌"]  # 使用第三方分词模块分词后的结果
>>> pinyin(words)
[['chéng'], ['yǔ'], ['hé'], ['shī'], ['gē']]
```
