### ISSUE TITLE
‘的确’的拼音错误

### ISSUE THREAD

**Issue by baizilong** [mozillazg/python-pinyin#231]
## 运行环境

* 操作系统（Linux）：
* Python 版本：2.7.12
* pypinyin 版本：0.36.0

## 问题描述

以下两句中的‘的确’不论是分词还是pinyin都是错误的：
‘每股24.67美元的确定性协议’
‘另有至少139例正等待国家卫生部的确认’
1、在现有的框架下，这种分词和pinyin错误的情况有没有解决方案？
2、扒开代码发现作者用FMM分词，一般BMM分词的效果会好一些，有没有考虑用BMM分词？
3、扒开词库看，发现有很多没有多音字的词也在词库里，这些词有没有必要放在词库里呢？

    多谢作者回答！

**Comment by mozillazg** [comment]
@baizilong 感谢反馈！

> 1、在现有的框架下，这种分词和pinyin错误的情况有没有解决方案？

可以使用其他分词模块先对字符串进行分词然后把分词后的结果列表作为 pinyin/lazy_pinyin 函数的参数： https://pypinyin.readthedocs.io/zh_CN/master/api.html#pypinyin.pinyin

```python
# 使用其他分词模块分词，比如 jieba 之类，或者基于 phrases_dict.py 里的词语数据使用其他分词算法分词
>>> words = list(jieba.cut('每股24.67美元的确定性协议'))  
>>> pinyin(words)
```

> 2、扒开代码发现作者用FMM分词，一般BMM分词的效果会好一些，有没有考虑用BMM分词？

等我有空的时候试试 BMM分词，不过分词不是这个项目的重点，优先级会低一点。

> 3、扒开词库看，发现有很多没有多音字的词也在词库里，这些词有没有必要放在词库里呢？

最新版本已经做过处理了，phrases_dict.py 里的词语都是至少有一个字是多音字。

**Comment by sxh19911230** [comment]
@mozillazg 
> 最新版本已经做过处理了，phrases_dict.py 里的词语都是至少有一个字是多音字。

其实可以把默认的都给处理掉，比如说，重 有chong和zhong，如果默认的是zhong，就把phrases_dict.py 里 重 读音为zhong去除了，这样不会对结果产生影响，而且我觉得至少能把词典大小减去一半。（假设默认读音单词更多的话）

> 可以使用其他分词模块先对字符串进行分词然后把分词后的结果列表作为 pinyin/lazy_pinyin 函数的参数： https://pypinyin.readthedocs.io/zh_CN/master/api.html#pypinyin.pinyin

还有就是我觉得可以把 phrase_pinyin 也放到让外面让别人用，这样就可以解决有人想用jieba分词的问题了。

**Comment by mozillazg** [comment]
@sxh19911230 

> 其实可以把默认的都给处理掉，比如说，重 有chong和zhong，如果默认的是zhong，就把phrases_dict.py 里 重 读音为zhong去除了，这样不会对结果产生影响，而且我觉得至少能把词典大小减去一半。（假设默认读音单词更多的话）

去掉会对结果产生影响。因为词语中的多音字的读音是在词语中才有意义，词语里删除一个字的话，就无法构成一个词语了，也就无法判断多音字应该读取哪个音。

> 还有就是我觉得可以把 phrase_pinyin 也放到让外面让别人用，这样就可以解决有人想用jieba分词的问题了。

现在的【把分词后的结果列表作为 pinyin/lazy_pinyin 函数的参数】的方法已经解决了【有人想用jieba分词】的问题。

**Comment by sxh19911230** [comment]
@mozillazg 

> 去掉会对结果产生影响。因为词语中的多音字的读音是在词语中才有意义，词语里删除一个字的话，就无法构成一个词语了，也就无法判断多音字应该读取哪个音。

能给个栗子吗？我举个栗子吧，比如说 重庆 重心，假如 重 的默认读音是zhong，然后我们把 重心 从phrases_dict.py删了，然后由于他找不到 重心，所以去用默认的single_pinyin来返回，也会返回 zhong xin，因为zhong是默认的，重庆没有删，所以仍旧会返回chong qing

**Comment by mozillazg** [comment]
@sxh19911230 例子：

```
>>> # 在词组中
>>> pinyin('重心', heteronym=True)
[['zhòng'], ['xīn']]
>>>
>>> # 模拟不在词组中
>>> pinyin(['重', '心'], heteronym=True)
[['zhòng', 'chóng', 'tóng'], ['xīn']]
```
