### ISSUE TITLE
重了的拼音不太准确

### ISSUE THREAD

**Issue by WangWenQiang** [mozillazg/python-pinyin#238]
## 运行环境

* 操作系统: macOS
* Python 版本：3.7.6
* pypinyin 版本 0.41.0

## 问题描述
重和了的最后一个多音是哪里来的，不太准确
[['zhong4', 'chong2', 'tong2'], ['le', 'liao3', 'liao4']]
## 问题复现步骤
pypinyin.pinyin('重了', style=pypinyin.TONE3, heteronym=True)

**Comment by mozillazg** [comment]
@WangWenQiang 感谢反馈！我确认一下。

**Comment by WangWenQiang** [comment]
你的邮件我已收到，谢谢！
