### ISSUE TITLE
符号 "|" 

### ISSUE THREAD

**Issue by maxinewell** [mozillazg/python-pinyin#240]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Linux
* Python 版本：3.7.10
* pypinyin 版本：0.41.0

## 问题描述

符号 "|" 读 gun 无法去除

**Comment by mozillazg** [comment]
@maxinewell 是想覆盖这个字的读音吗？可以参考 https://pypinyin.readthedocs.io/zh_CN/master/usage.html#custom-dict 这个文档里的 `load_single_dict`  函数的用法进行覆盖。
