### ISSUE TITLE
【胶】字的拼音错误

### ISSUE THREAD

**Issue by lvhey** [mozillazg/python-pinyin#248]
## 运行环境

* 操作系统（Linux/macOS/Windows）：win10
* Python 版本：3.9.6
* pypinyin 版本：0.4.0

## 问题描述
胶 的拼音错误，输出为xiáo

**Comment by mozillazg** [comment]
```
>>> pinyin('胶')
[['jiāo']]
>>> pinyin('胶', heteronym=True)
[['jiāo', 'xiáo']]
```

没明白具体问题是啥，是说结果里不应该有 `xiáo` 吗？
胶 确实是有 `xiáo` 这个读音的：http://zisea.com/zscontent.asp?uni=80F6

**Comment by lvhey** [comment]
是这样，我在脚本中读取到的词是 “橡胶” ，转换后的拼音为 “xiàngxiáo”。

print(pinyin.get_pinyin("橡胶"))
xiàngxiáo

而且我用 get_pinyin("胶") 时，得到的拼音也是 xiáo。

我认为 jiāo 这个拼音应该更常用一些

**Comment by mozillazg** [comment]
@lvhey 你用的这个 `pinyin` 模块不是这个项目，这个项目没有一个叫 `get_pinyin` 的函数或方法。

**Comment by lvhey** [comment]
对不起，打扰了🙇‍♂️🙇‍♂️
