### ISSUE TITLE
v_to_u的详细规则

### ISSUE THREAD

**Issue by VisualJoyce** [mozillazg/python-pinyin#251]
从以下例子，感觉`v_to_u`的规则似乎不一致。

![image](https://user-images.githubusercontent.com/36122522/136135133-d0abc69b-9857-481e-ad45-9c83b62ba4ba.png)

能否简要说明一下。

**Comment by mozillazg** [comment]
没看出来问题是啥？

**Comment by VisualJoyce** [comment]
音调没有异议，感觉上最后一个例子输出应该是`nve5`

**Comment by VisualJoyce** [comment]
![image](https://user-images.githubusercontent.com/36122522/136138042-7ba45558-15d1-454d-9111-cb3afcab432c.png)
这个好像没有起作用

**Comment by mozillazg** [comment]
> ![image](https://user-images.githubusercontent.com/36122522/136138042-7ba45558-15d1-454d-9111-cb3afcab432c.png) 这个好像没有起作用

嗯，这个应该是个 bug。
