### ISSUE TITLE
【咁】的读音中【han】是否多余？

### ISSUE THREAD

**Issue by VisualJoyce** [mozillazg/python-pinyin#254]
![image](https://user-images.githubusercontent.com/36122522/136659827-cfb208e3-c839-4457-9383-177c0b0a3e03.png)

**Comment by mozillazg** [comment]
<img width="639" alt="image" src="https://user-images.githubusercontent.com/485054/141644956-208ba51c-b2e1-4458-a64a-0130c7520e1d.png">

看起来不是多余的：https://www.homeinmists.com/hd/orgpage.html?page=646
