### ISSUE TITLE
能否在Style.TONE3中将数字换成音调符号？

### ISSUE THREAD

**Issue by ilsoviet1917** [mozillazg/python-pinyin#257]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Windows
* Python 版本：3.9.6
* pypinyin 版本：0.42.0

## 问题描述
能否在Style.TONE3中将数字换成音调符号？

比如：国家：[['guo2'], ['jia1']]显示为：[['guoˊ'], ['jia1ˉ]

四声符号的unicode码为
ˉ    U+02C9
ˊ    U+02CA
ˇ    U+02C7
ˋ    U+02CB

**Comment by ilsoviet1917** [comment]
在文字和数字混排的时候，音调的1-4和数字的1-4无法区分，数字的1-4也会被替换掉。

**Comment by mozillazg** [comment]
@ilsoviet1917 可以通过 [自定义拼音风格](https://pypinyin.readthedocs.io/zh_CN/master/api.html#convert-style) 来实现这个需求：

```python
from pypinyin.style.tone import ToneConverter
from pypinyin.style import register
from pypinyin import pinyin

new_style = 'tone3_with_variant'

@register(new_style)
def tone3_with_variant(pinyin, **kwargs):
    tone3 = ToneConverter().to_tone3(pinyin, **kwargs)
    # 处理示例
    return tone3.replace('2', 'ˊ')

print(pinyin('国家abc123', style=new_style))
# [['guoˊ'], ['jia1'], ['abc123']]
```
