### ISSUE TITLE
lazy_pinyin的FINALS_TONE3模式如何自定义？

### ISSUE THREAD

**Issue by ilsoviet1917** [mozillazg/python-pinyin#258]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Windows
* Python 版本：3.9.6
* pypinyin 版本：0.42.0

## 问题描述
lazy_pinyin的FINALS_TONE3模式如何自定义？
将韵母+数字音调的模式改为韵母+符号音调
比如：国家：[['uo2'], ['ia1']]显示为：[['uoˊ'], ['iaˉ]

**Comment by mozillazg** [comment]
可以参考 https://github.com/mozillazg/python-pinyin/issues/257 里的代码自行实现。
