### ISSUE TITLE
嗯"的韵母似乎出错了

### ISSUE THREAD

**Issue by Rango94** [mozillazg/python-pinyin#259]
## 运行环境

* 操作系统（Linux/macOS/Windows）：macos
* Python 版本：3.6
* pypinyin 版本：0.43

## 问题描述
"嗯"的韵母似乎出错了

## 问题复现步骤
>>> from pypinyin import Style, pinyin
>>> pinyin("蒽", style=Style.FINALS, strict=False)
[['en']]
>>> pinyin("嗯", style=Style.FINALS, strict=False)
[['n']]

**Comment by mozillazg** [comment]
没明白啥意思。是跟 https://github.com/mozillazg/python-pinyin/issues/109 这个类似的问题不？

**Comment by Rango94** [comment]
> 没明白啥意思。是跟 #109 这个类似的问题不？

原来如此，涨知识了。。
