### ISSUE TITLE
多进程下加载新词典的问题

### ISSUE THREAD

**Issue by Moonmore** [mozillazg/python-pinyin#264]
非常感谢作者贡献的工作，最近在使用您的这个工具有一个问题？
就是在多进程下load新词典进去，相同字不同音，或者同音不同字的情况会影响多进程下的工作吗，比如进程1 想标出 （你好  ni3 hao3），进程2（你好 ni2 hao3），这样的情况下后续的词典load会影响到前面的一个读音。

**Comment by mozillazg** [comment]
是的，这个库里的词典是全局共享的。
