### ISSUE TITLE
词典中所有韵母

### ISSUE THREAD

**Issue by MianWang123** [mozillazg/python-pinyin#266]
请问下怎样可以获取词库中所有存在的韵母？我想把所有可能出现的韵母提取出来，是否可行呢？

**Comment by mozillazg** [comment]
* 汉语拼音的所有韵母可以直接参考教育部的 [《汉语拼音方案》](http://www.moe.gov.cn/jyb_sjzl/ziliao/A19/195802/t19580201_186000.html) ，拼音方案里有列出所有的韵母。
* 或者参考这个两个 issue: https://github.com/mozillazg/python-pinyin/issues/244 https://github.com/mozillazg/python-pinyin/issues/225

**Comment by MianWang123** [comment]
我发现有些韵母都超出了《汉语拼音方案》的范围，比方说：呦-io，嗯-n

**Comment by JohnHerry** [comment]
> 

哟  yo  嗯 ng

**Comment by mozillazg** [comment]
> 我发现有些韵母都超出了《汉语拼音方案》的范围，比方说：呦-io，嗯-n，呣-m，是不是不太合理？

> 呦

这个没有复现，最新版得到的韵母是 iou:

```python
>>> pinyin('呦', style=Style.FINALS_TONE)
[['iōu']]
```

`嗯-n，呣-m` 这几个是有点模糊的特殊 case，暂时还没决定是否需要处理：https://github.com/mozillazg/python-pinyin/issues/80

**Comment by MianWang123** [comment]
> > 我发现有些韵母都超出了《汉语拼音方案》的范围，比方说：呦-io，嗯-n，呣-m，是不是不太合理？
> 
> > 呦
> 
> 这个没有复现，最新版得到的韵母是 iou:
> 
> ```python
> >>> pinyin('呦', style=Style.FINALS_TONE)
> [['iōu']]
> ```
> 
> `嗯-n，呣-m` 这几个是有点模糊的特殊 case，暂时还没决定是否需要处理：#80

不好意思，打错字了，是 “哟” - yo，然后韵母是 “io”

**Comment by mozillazg** [comment]
> 不好意思，打错字了，是 “哟” - yo，然后韵母是 “io”

@MianWang123 嗯，这个看起来是个 bug，等我有空的时候优化一下韵母相关函数，确保在 `strict=True` 的情况下只返回《汉语拼音方案》中列出的韵母。
