### ISSUE TITLE
“甚”拼音错误

### ISSUE THREAD

**Issue by JohnHerry** [mozillazg/python-pinyin#267]
## 运行环境

* 操作系统（Linux/macOS/Windows）：CentOS7
* Python 版本：3.6
* pypinyin 版本：0.43.0

## 问题描述

  “甚”拼音错误。
  “甚有前人遗风”  被pypinyin 读成 shen2
  “干甚么”   被pypinyin读成shen4
  两者反了。

## 问题复现步骤

pypinyin.pinyin(例句, style=pypinyin.TONE3)

**Comment by mozillazg** [comment]
感谢反馈!
