### ISSUE TITLE
Is it possible to split Pinyin into consonant and vowel?

### ISSUE THREAD

**Issue by shipleyxie** [mozillazg/python-pinyin#268]
Since the pronunciation of all syllables in Mandarin Chinese can be expressed in the combination of two phonemes which are called consonant and vowel.
Is it possible to use your great project to achieve this goal?

**Comment by mozillazg** [comment]
@shipleyxie 
This project doesn't support consonant and vowel. 
It supports initials (声母; 聲母; shēngmǔ) and finals (韵母; 韻母; yùnmǔ): https://en.wikipedia.org/wiki/Pinyin#Initials_and_finals
