### ISSUE TITLE
词语“种下”拼音有误

### ISSUE THREAD

**Issue by wta2001** [mozillazg/python-pinyin#269]
## 运行环境

* 操作系统：Linux
* Python 版本：3.10
* pypinyin 版本：0.45.0

## 问题描述
pinyin('种下一颗种子')
[['zhǒng'], ['xià'], ['yī'], ['kē'], ['zhǒng'], ['zi']]
在引入kxhc1983词库后拼音会变为
pinyin('种下')
[['chóng'], ['xià']]
## 问题复现步骤
pinyin('种下')
[['zhǒng'], ['xià']]

**Comment by mozillazg** [comment]
感谢反馈，你可以暂时先通过自定义词语拼音库的方式修正 `种下` 的结果：

https://pypinyin.readthedocs.io/zh_CN/master/usage.html#custom-dict
