### ISSUE TITLE
支持从拼音到中文的转换吗

### ISSUE THREAD

**Issue by niminjian** [mozillazg/python-pinyin#272]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：
* pypinyin 版本：

**Comment by niminjian** [comment]
您好，请问是否支持从拼音到中文的转换

**Comment by mozillazg** [comment]
@niminjian 可以看一下这个：https://github.com/mozillazg/python-pinyin/issues/184
