### ISSUE TITLE
不支援英文字母以及數字

### ISSUE THREAD

**Issue by b07902011** [mozillazg/python-pinyin#274]
## 运行环境

* 操作系统（Linux/macOS/Windows）： Linux
* Python 版本：3.9
* pypinyin 版本：0.46.0

## 问题描述
希望可以支援 "AI", "3000" 這樣子的組合

**Comment by mozillazg** [comment]
@b07902011 可以详细说明一下具体需求吗？没明白【希望可以支援 "AI", "3000" 這樣子的組合】具体是啥需求，是否可以举例说明，对于 `AI` 这个输入期望的输出是啥样的？
