### ISSUE TITLE
我想用C#实现一样的功能，能给讲讲实现的思路吗？

### ISSUE THREAD

**Issue by ilsoviet1917** [mozillazg/python-pinyin#276]
我看了你的代码，但是看不懂。能否请给讲讲实现思路？

**Comment by mozillazg** [comment]
可以看这个 convert 方法，当前版本主逻辑的入口是这个方法：https://github.com/mozillazg/python-pinyin/blob/master/pypinyin/converter.py#L33

老版本的实现思路（跟当前版本的核心思路是一样的）：https://pypinyin.readthedocs.io/zh_CN/develop/develop.html#id5 ，可以配合之前的老版本代码一起看：
https://github.com/mozillazg/python-pinyin/tree/v0.27.0/pypinyin

**Comment by ilsoviet1917** [comment]
TONE3这种注音风格怎么实现的呢？比如ā怎么抓换成a1？

**Comment by mozillazg** [comment]
@ilsoviet1917 

> 1.TONE3这种注音风格怎么实现的呢？比如ā怎么转换成a1？
> 2.声母和韵母是怎么区分开的？

不同拼音风格的处理逻辑都在 https://github.com/mozillazg/python-pinyin/tree/v0.27.0/pypinyin/style 这个文件夹下面

> 3.我看您写的实现思路里有“检查词条”，在整段汉语中，是否是要先分成不同的词，然后再在相应的DICT中取出对应拼音？词如何分是不是要通过某种特定的算法？对于单字的处理，我看是通过“PINYIN_DICT”取拼音，但是我好像没看到这个文件。
>> 在整段汉语中，是否是要先分成不同的词，然后再在相应的DICT中取出对应拼音？词如何分是不是要通过某种特定的算法？

是的，会分词。你可以用第三方分词库（一般各个语言都有现成的第三方分词库）进行分词也可以自己写个分词库。具体的算法有很多种，可以搜索一下【中文分词】相关知识。

>> 对于单字的处理，我看是通过“PINYIN_DICT”取拼音，但是我好像没看到这个文件。 

这个不是一个文件的名称，是一个变量的名称，你可以直接对 pypinyin 目录下的所有文件进行一次全文搜索就可以找到了。
