### ISSUE TITLE
一些多音字会注解错误

### ISSUE THREAD

**Issue by oldcai** [mozillazg/python-pinyin#28]
『卡』字的拼音总是注音成 qia
网卡
显卡

『莎』suo
浪莎

**Comment by mozillazg** [comment]
@oldcai 如果你用的是 `lazy_pinyin` 这个函数的话，出现这种情况是因为：

* 词组拼音库中没有包含这个词语
* 单字拼音库中 `卡` 字的第一个读音是 `qia`
* `lazy_pinyin` 取的是单字的第一个读音

解决办法可以参考 #15 （通过 `load_phrases_dict` 或 `load_single_dict` 调整拼音库）。
