### ISSUE TITLE
拼音风格转换问题，'xv2','jv4','qv4'

### ISSUE THREAD

**Issue by fangqiang817** [mozillazg/python-pinyin#281]
## 问题描述
ü见了j q x，应该去掉两点

## 问题复现步骤

```
from pypinyin.contrib.tone_convert import to_tone

# 徐、据、去
py_lst = ['xv2','jv4','qv4']

for p in py_lst:
    print(to_tone(p))
```

output:
xǘ
jǜ
qǜ

没有上述结果的拼音

**Comment by mozillazg** [comment]
感谢反馈！

**Comment by mozillazg** [comment]
仔细看了一下，`'xv2','jv4','qv4'` 这几个拼音的输入就是错的，正确应该是 `xu2`, `ju4`, `qu4`。pypinyin 不会输出 `'xv2','jv4','qv4'` 这种拼音结果。
