### ISSUE TITLE
BOPOMOFO of "誒" and "欸" includes "ê"

### ISSUE THREAD

**Issue by stefantaubert** [mozillazg/python-pinyin#291]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Linux
* Python 版本：3.10.8
* pypinyin 版本：0.47.1

## 问题描述

Retrieving BOPOMOFO of `誒` and `欸` returns invalid results which include `ê`.

## 问题复现步骤

```py
from pypinyin import Style, pinyin

print(pinyin("誒", Style.BOPOMOFO, heteronym=True))
# [['ㄟˊ', 'ㄒㄧ', 'ㄧˋ', 'ê', 'êˊ', 'êˇ', 'ㄟˇ', 'êˋ', 'ㄟˋ', 'ㄟ']]
print(pinyin("欸", Style.BOPOMOFO, heteronym=True))
# [['ㄞ', 'ㄞˇ', 'ê', 'êˊ', 'êˇ', 'êˋ', 'ㄒㄧㄝˋ', 'ㄟˊ', 'ㄟˇ', 'ㄟˋ', 'ㄟ']]
```

**Comment by mozillazg** [comment]
@stefantaubert Thanks for reporting. I'll take a look at it.
