### ISSUE TITLE
"称手" 读音有误

### ISSUE THREAD

**Issue by frankrx41** [mozillazg/python-pinyin#295]
## 运行环境

* 操作系统： Windows
* Python 版本：  3.10.5
* pypinyin 版本：  0.48.0, 0.47.1

## 问题描述
"称手" 读音有误
正确读音应该为 chèn shǒu

称手，谓使用起来顺手。
https://www.zdic.net/hans/%E7%A7%B0%E6%89%8B

## 问题复现步骤

```cmd
>pypinyin 称手
chēng shǒu
>pypinyin 稱手
chēng shǒu
```

**Comment by mozillazg** [comment]
感谢反馈！
