### ISSUE TITLE
佛 字在“佛系”中注音错误

### ISSUE THREAD

**Issue by Danran0228** [mozillazg/python-pinyin#296]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Windows
* Python 版本：3.10.7
* pypinyin 版本：0.48.0

## 问题描述
在“佛系”中拼音应该为 [‘fó‘， ‘xì‘]，实际返回的是 ['fú', 'xì']

**Comment by mozillazg** [comment]
感谢反馈！
