### ISSUE TITLE
“了”字在一死了之中注音错误

### ISSUE THREAD

**Issue by Danran0228** [mozillazg/python-pinyin#298]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Windows
* Python 版本：3.10.7
* pypinyin 版本：0.48.0

## 问题描述
在词语“一死了之”中拼音应该为['yī', 'sǐ', 'liǎo', 'zhī']，实际注音为['yī', 'sǐ', 'le', 'zhī']

**Comment by mozillazg** [comment]
感谢反馈！
