### ISSUE TITLE
分词应加入用户词典的词汇，发生读取词典后依然显示错误的情况

### ISSUE THREAD

**Issue by oldcai** [mozillazg/python-pinyin#30]
```
load_phrases_dict({u'弹力素': [[u'tan'], [u'li'], u['su']]})
print lazy_pinyin(u'弹力素', style=NORMAL, errors=handle_error)
```

Output: [u'dan', u'li', u'su']

是分词的问题。把弹力素切成两个词了。只加入'弹力'就好了。
但是希望能把用户词典里的词能添加到结巴中当做单独的词汇。

**Comment by mozillazg** [comment]
@oldcai 当前这个库并没有强依赖结巴分词。对于要使用结巴分词的用户应该自己去调教 jieba（[文档](https://github.com/fxsjy/jieba#2-添加自定义词典)）。
