### ISSUE TITLE
pinyin(“流”, style=5, heteronym=False) 返回 iou，应该是iu

### ISSUE THREAD

**Issue by Caisen2012** [mozillazg/python-pinyin#300]

**Comment by mozillazg** [comment]
@Caisen2012 当前的结果是预期的。如果不符合你的预期的话，可能你想要的是 `strict=False` 时的结果。关于这个参数的说明详见：https://pypinyin.readthedocs.io/zh_CN/master/usage.html#strict

**Comment by Caisen2012** [comment]
您的邮件已收到。

**Comment by Caisen2012** [comment]
您的邮件已收到。
