### ISSUE TITLE
关于太子参中的多音字，参的读音

### ISSUE THREAD

**Issue by AIKoumei** [mozillazg/python-pinyin#301]
感谢作者大大的项目，非常方便好用。
在使用中遇到了 参 的读音问题。

## 运行环境

* 操作系统（Linux/macOS/Windows）：windows 10
* Python 版本：3.10.6
* pypinyin 版本： 0.48.0

## 问题描述
太子参 的 参 返回了 `['cān']` 而非 `['shēn']` 。

太子参 在命令 `pypinyin.pinyin("太子参", style=pypinyin.NORMAL)` 和 `pypinyin.pinyin("太子参", heteronym=True)` 中返回了一样的结果 `[['tài'], ['zi'], ['cān']]`。
1、参 是多音字，在多音字方法中是否需要返回类似于 `[['tài'], ['zi'], [''cān'', 'shēn']]` ？
2、太子参 的正确读音是 `[['tài'], ['zi'], ['shēn']]` 而非 `[['tài'], ['zi'], ['cān']]`

但是 人参 的返回却是 `[['rén'], ['shēn']]` ，是否上述代码中有遗漏的参数？

## 问题复现步骤
`print(pypinyin.pinyin("太子参", style=pypinyin.NORMAL))`
`print(pypinyin.pinyin("太子参", heteronym=True))`
`print(pypinyin.pinyin("人参", style=pypinyin.NORMAL))`
`print(pypinyin.pinyin("人参", heteronym=True))`

**Comment by mozillazg** [comment]
@AIKoumei 感谢反馈！我将在新版中解决这个问题，当前你可以先使用以下文档中的方法 workaround 一下：
https://pypinyin.readthedocs.io/zh_CN/master/usage.html#custom-dict
