### ISSUE TITLE
想问一下作者大佬多音字是怎么判断该用哪个读音的

### ISSUE THREAD

**Issue by piano-accordion** [mozillazg/python-pinyin#306]
想问一下作者大佬多音字是怎么判断该用哪个读音的，是用词表之类的规则来做，还是可以用深度学习做呢～印象里输入法里的拼音支持的很完善，不知道他们又是怎么做的。

**Comment by mozillazg** [comment]
> 是用词表之类的规则来做

当前 pypinyin 用的是这个方法，准确性不是很好。

> 还是可以用深度学习做

如果对准确性要求更高的话，更推荐用类似的方法实现。

之前关于这个的讨论详见：https://github.com/mozillazg/python-pinyin/issues/133#issuecomment-935353958

> 印象里输入法里的拼音支持的很完善，不知道他们又是怎么做的。

关于输入法的实现，可以参考 https://github.com/mozillazg/python-pinyin/issues/184#issuecomment-1020713719 这里提到的项目，
或者参考知名输入法 rime 的实现：https://github.com/rime/librime 。
