### ISSUE TITLE
[feature] Cache old results to `~/.cache/pinyin/pinyin.history` and use the old result to fasten

### ISSUE THREAD

**Issue by Freed-Wu** [mozillazg/python-pinyin#309]
Cache old results to `~/.cache/pinyin/pinyin.history` and use the old result to fasten

**Comment by mozillazg** [comment]
Thanks for your suggestion. But I'm too busy to do it. Feel free to send a pull request.

IMHO, this feature should be optional and is disabled by default.

**Comment by Freed-Wu** [comment]
Currently I use cpp-pinyin to replace pypinyin to speed up, looks like better than cache.
