### ISSUE TITLE
[feature] Generate a cache to store all pinyin of characters

### ISSUE THREAD

**Issue by Freed-Wu** [mozillazg/python-pinyin#310]
Comes from <https://github.com/petronny/pinyin-completion/issues/18>:

ngram is not fast. Can this project provide a tool to generate a cache (format can be json or other formats) to store all pinyin of characters? Such as:

```sh
python -m pypinyin.tools.generate_cache --format=json --style=FIRST_LETTER > /the/path/of/pinyin_FIRST_LETTER.json
jq -S . /the/path/of/pinyin_FIRST_LETTER.json
{
...
"你": "n"
"您": "n"
...
}
# a very large json
```

**Comment by mozillazg** [comment]
Thanks for your suggestion. But I'm too busy to do it. Feel free to send a pull request.

IMHO, some names like `generate_all_pinyins` may be a better name than `generate_cache`.

**Comment by Freed-Wu** [comment]
Currently I use cpp-pinyin to replace pypinyin to speed up, looks like better than cache.
