### ISSUE TITLE
用 vscode debugger 启动时，`import pypinyin` 语句会花费很长时间（10min左右）

### ISSUE THREAD

**Issue by LifeJustDLC** [mozillazg/python-pinyin#322]
## 运行环境

* 操作系统（Linux/macOS/Windows）：Windows10
* Python 版本：3.10~3.12 都试过
* pypinyin 版本：0.51.0

## 问题描述

用 vscode debugger 启动时，`import pypinyin` 语句会花费很长时间（10min左右），期间 CPU 占用略高（20%）。
正常 `python ./script.py` 和在 REPL 里 import 都没问题。不确定是不是 vscode debugger 的问题，总之两边都提交了 issue。

mac 上测试过没问题，**问题只在 windows 上出现**

（怀疑过 conda，venv，但去掉后还是一样）

## 问题复现步骤

用 vscode debugger 执行：
```python
# test.py
print("before")
import pypinyin
print("after") # 此句打上断点
```

**Comment by yafacex** [comment]
同问

**Comment by mozillazg** [comment]
嗯，可以参考一下 https://github.com/mozillazg/python-pinyin/issues/319 这个 issue 中提供的方法，看看是否有帮助。

**Comment by serfend** [comment]
可以考虑把`pinyin_dict.py`改成加载器。
```python
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
import json

# Warning: Auto-generated file, don't edit.
with open("./test_dict.json", "r", encoding="utf-8") as f:
    pinyin_dict = json.loads(f.read())
```

**Comment by mozillazg** [comment]
发布了一个缓解这个问题的 dev 版本（改动详见 https://github.com/mozillazg/python-pinyin/pull/324 , Thanks @serfend ），麻烦大家有空的时候帮忙验证一下问题是否还存在，谢谢~ 

```
pip install pypinyin==0.52.0.dev1
```

**Comment by mozillazg** [comment]
正式的优化该问题的 0.52.0 版本已发布。
