### ISSUE TITLE
同样的输入，string 和 list 的结果不同。。。

### ISSUE THREAD

**Issue by daming-lu** [mozillazg/python-pinyin#323]
![20240703-164654](https://github.com/mozillazg/python-pinyin/assets/5635322/2d858c8b-6bd4-4253-848a-f1baff91a62d)

了却君王天下事
list 是 ‘le’
string 是 ‘liao’ 

玄幻。。。

**Comment by mozillazg** [comment]
> 参数值为列表时表示输入的是已分词后的数据
https://github.com/mozillazg/python-pinyin?tab=readme-ov-file#%E4%BD%BF%E7%94%A8%E7%A4%BA%E4%BE%8B

输入是 string 的时候内部会做二次分词，输入是 list 的时候会跳过这个分词步骤。
