### ISSUE TITLE
Use pyinstaller to compile my app

### ISSUE THREAD

**Issue by GuyMicciche** [mozillazg/python-pinyin#328]
Hello, i have used your package in my app. when i use pyinstaller to compile my app, it doesn't include your package. why? can you please help?

**Comment by mozillazg** [comment]
@GuyMicciche Does it raise errors like `no such file or dictionary: pinyin_dict.json`? You can fix it by modifying the app.spec file:

```
from PyInstaller.utils.hooks import collect_data_files   // add

a = Analysis(
    ['main.py'],
    datas=collect_data_files('pypinyin'),   //  add
    ....
)

// or
resources  = ...
resources += collect_data_files('pypinyin')
a = Analysis(
    ['main.py'],
    datas=resources,
    ....
)
```

ref: https://pyinstaller.org/en/stable/runtime-information.html#placing-data-files-at-expected-locations-inside-the-bundle

**Comment by xushengj** [comment]
You may instead add `--collect-data pypinyin` when invoking `pyinstaller` to work around this problem (which is what I'm doing).

**Comment by GuyMicciche** [comment]
> You may instead add `--collect-data pypinyin` when invoking `pyinstaller` to work around this problem (which is what I'm doing).

Thank you! This worked for me!
