### ISSUE TITLE
同音词替换功能？

### ISSUE THREAD

**Issue by Tint0ri** [mozillazg/python-pinyin#336]
## 运行环境

* 操作系统（Linux/macOS/Windows）：
* Python 版本：
* pypinyin 版本：

## 问题描述
能否增加一个同音词替换功能，例如：

replace_homophones(source, replace, mode)

如果在source字符串中存在符合mode拼音模式匹配的replace字符串的子串，就用replace替换source中的子串并返回
mode模式可以包括：

1. 拼音相同
2. 拼音及音调相同
3. 声母相同
4. 支持模糊音？
5. 支持多音字？

感觉这个功能有很多应用场景，比如根据专业词汇表校正通用语音识别后的文本

**Comment by mozillazg** [comment]
@Tint0ri 暂时没有这个计划。这个需求看起来似乎可以基于这个项目对外提供的函数进行实现，不强依赖项目本身提供该功能？

**Comment by Tint0ri** [comment]
好的。
