### ISSUE TITLE
关于分词

### ISSUE THREAD

**Issue by ljhierarch** [mozillazg/python-pinyin#38]
core.py中的pinyin 方法
 for words in hans:
        pys.extend(_pinyin(words, style, heteronym, errors))
这个地方用的是extend，导致即使使用了jieba分词，分出来的结果还是返回一个一个汉字的拼音list
区别不出来那几个是一个词语，跟没分一样。。

**Comment by mozillazg** [comment]
分词的目的是为了处理多音字的问题。
