### ISSUE TITLE
TO3NE 或 TONE3

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/python-pinyin#39]
https://github.com/hotoo/pinyin 的实现是：

> TONE 标准声调风格
> TONE2 声调以数字形式在末尾的风格（当初我这样命名的原因）
> TO3NE 声调以数字形式在中间的风格

详见：https://github.com/hotoo/pinyin/issues/79

考虑是否改为它这种风格。

**Comment by Artoria2e5** [comment]
这个和现在 API 写得不一样欸……

https://pypinyin.readthedocs.io/en/master/api.html
