### ISSUE TITLE
[BUG]INITIALS模式下很多字没法正确解析

### ISSUE THREAD

**Issue by cysnake4713** [mozillazg/python-pinyin#44]
使用的是python 3.4
pypinyin.slug('王', pypinyin.INITIALS, separator='')

无法正确获得 ‘y’， 而返回一个空串

**Comment by hotoo** [comment]
https://github.com/hotoo/pinyin#为什么没有-y-w-yu-几个声母

**Comment by cysnake4713** [comment]
涨姿势！！！
