### ISSUE TITLE
STYLE_BOPOMOFO（注音符号）

### ISSUE THREAD

**Issue by Artoria2e5** [mozillazg/python-pinyin#48]
对岸常用的注音符号是可以从拼音数据转换出来的，至于语文标准审定字音那也不是这个项目的事情。

可以参考 https://github.com/The-Orizon/nlputils/blob/master/libpinyin_bopomofo.py 的转换（我也不知道 tone2 是什么格式，本来看文档还以为是 to2ne 呢）。

|Style|Desc|
|----|------|
|STYLE_BOPOMOFO|普通的带声调注音。注音的声调永远在最后，阴平（第一声）不标。|
|STYLE_BOPOMOFO_NOTONE|没声调。|

注音本身可以说有类似双拼的特性。

**Comment by gumblex** [comment]
没声调的似乎没多大用？不如来个 BOPOMOFO_INITIALS
我在实现相应功能

**Comment by mozillazg** [comment]
@Artoria2e5 我对注音不大了解，你觉得呢？
@gumblex  期待 👍

**Comment by Artoria2e5** [comment]
gumblex 一直都是对的。（

**Comment by gumblex** [comment]
@Artoria2e5 ??? :new_moon_with_face: ???
