### ISSUE TITLE
TONE2 未标轻声

### ISSUE THREAD

**Issue by gumblex** [mozillazg/python-pinyin#50]
如“打量”，输出 `[['da3'], ['liang']]`，文档中写“用数字 [0-4] 进行表示”。这种情况除了 ü 都有。请问该修文档还是程序行为？

**Comment by mozillazg** [comment]
@gumblex 感觉轻生没必要标个 0: `liang vs lia0ng` 一般来说看到没声调就可以知道是轻声了，加个 0 感觉就有点画蛇填足了。

所以，还是修改文档比较好，同时 ü 的 v0 改成 v 这样就统一了。

**Comment by gumblex** [comment]
啊之前还有个问题是 侵略 -> qi1n lu0e4
