### ISSUE TITLE
“了”没有音调？

### ISSUE THREAD

**Issue by xiaohk** [mozillazg/python-pinyin#53]
我试了下面的code：
```python
print(lazy_pinyin("了",style=1))      #['le']
print(pinyin("了",style=1))           #[['le']]
```

请问这是一个bug吗？😉

**Comment by xiaohk** [comment]
喔，是我没有仔细看，轻声的话就省略了。可以考虑return 0来代替轻声。

**Comment by mozillazg** [comment]
@xiaohk 嗯，我考虑一下。对于拼音来说没有声调表示的就是轻声，没有别的含义，所以就没标 0 了。参考 https://github.com/mozillazg/python-pinyin/issues/50
