### ISSUE TITLE
多音字问题

### ISSUE THREAD

**Issue by solos** [mozillazg/python-pinyin#56]
我发现有些字不是多音字也识别为多音字了，请问怎么避免这种情况呢

pinyin(u'分', heteronym=True)

fēn
fèn
fén
bàn

pinyin(u'平', heteronym=True)

píng
pián
bìng
bēng

**Comment by gumblex** [comment]
然而它们是多音字

**Comment by mozillazg** [comment]
是的，它们其实都是多音字。

**Comment by 5977862** [comment]
楼主low了，哈哈哈~ 中国文化博大精深

**Comment by solos** [comment]
谢谢 @gumblex @mozillazg
