### ISSUE TITLE
“妳”读音错误

### ISSUE THREAD

**Issue by zhuangh** [mozillazg/python-pinyin#58]
```
>>> from pypinyin import pinyin
>>> pinyin('你会')
[['nǐ'], ['huì']]
>>> pinyin('妳會')
[['nǎi'], ['huì']]
```

**Comment by arctanx0** [comment]
![image](https://cloud.githubusercontent.com/assets/7189225/22725959/7536fae0-ee0b-11e6-8650-5f70c644b7d1.png)

**Comment by zhuangh** [comment]
嗯，谢谢，“妳”的确如此。
那么应该如何得到正确的“妳會”=[['nǐ'], ['huì']]？ 
>>> pinyin('妳會', heteronym=True) 
[['nǎi', 'nǐ'], ['huì', 'kuài', 'kuò']]

**Comment by mozillazg** [comment]
@zhuangh 可以临时调整 `妳` 的拼音顺序:

```python
>>> from pypinyin import load_single_dict, pinyin
>>> load_single_dict({ord('妳'): 'nǐ,nǎi'})
>>> pinyin('妳會')
[['nǐ'], ['huì']]
```

**Comment by zhuangh** [comment]
@mozillazg 谢谢，所以改了吗？

**Comment by mozillazg** [comment]
@zhuangh 还没。可以用上面的方法临时调整一下。

**Comment by mozillazg** [comment]
@zhuangh 已改。麻烦更新为最新版。

**Comment by zhuangh** [comment]
@mozillazg thanks!

**Comment by mozillazg** [comment]
@zhuangh 不客气!
