### ISSUE TITLE
"厦门" convert to 'shamen'

### ISSUE THREAD

**Issue by finlay-liu** [mozillazg/python-pinyin#59]
when use `pypinyin.lazy_pinyin` or `pypinyin.pinyin`, it transform '厦门' to 'shamen', but the right output is 'xiamen'

**Comment by mozillazg** [comment]
还没找到一个很好的正确识别词组拼音的方法 😂 
目前用的是一个很笨的办法：通过词组拼音库的方式来指定词组的拼音。
