### ISSUE TITLE
内置一个按词语分词的分词模块

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/python-pinyin#63]
一个不太智能的，基于内置的词语库来分词的分词模块。

如果不想使用结巴分词可以先使用这个模块对字符串进行分词，然后再调用拼音相关的 API.

* [x] 最大正向匹配分词器
* [x] 测试分词器的准确率
* [x] 加载内置的词库
* [x] 测试使用分词器
* [ ] 文档

**Comment by gumblex** [comment]
用最大正向分词？

**Comment by mozillazg** [comment]
@gumblex 可以。

**Comment by onsunsl** [comment]
分词怎么使用？

**Comment by mozillazg** [comment]
@onsunsl 例子：http://pypinyin.readthedocs.io/zh_CN/master/usage.html#id6
