### ISSUE TITLE
串中含数字的bug

### ISSUE THREAD

**Issue by onsunsl** [mozillazg/python-pinyin#64]
In [20]: p = pinyin('人家才刚学会中文。。这么快就要学2外呀', style=3)

In [21]: p
Out[21]:
[['r'],
 ['j'],
 ['c'],
 ['g'],
 ['x'],
 ['h'],
 ['zh'],
 [''],
 ['。。'],
 ['zh'],
 ['m'],
 ['k'],
 ['j'],
 [''],
 ['x'],
 ['2'],
 [''],
 ['']]

**Comment by mozillazg** [comment]
@onsunsl 因为 `y`, `w` 不是声母. 详见 #27

**Comment by mozillazg** [comment]
你可能需要的是 `style=pypinyin.FIRST_LETTER`:

```python
In [2]: p = pypinyin.pinyin('人家才刚学会中文。。这么快就要学2外呀', style=pypinyin.FIRST_LETTER)

In [3]: p
Out[3]:
[['r'],
 ['j'],
 ['c'],
 ['g'],
 ['x'],
 ['h'],
 ['z'],
 ['w'],
 ['。。'],
 ['z'],
 ['m'],
 ['k'],
 ['j'],
 ['y'],
 ['x'],
 ['2'],
 ['w'],
 ['y']]


```
