### ISSUE TITLE
使用 phrase-pinyin-data 的数据自动生成词语拼音库

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/python-pinyin#66]
https://github.com/mozillazg/phrase-pinyin-data

**Comment by onsunsl** [comment]
我在收集了一些多音字词组
怎么提交？
我的mail: onsunsl@qq.com

**Comment by onsunsl** [comment]
这我安装了jieba分词，然后合适lazy_pinyin
还有近两2k个词多字不正确
我这的词都是zhi 这种格式的，怎么转成你的数据格式

**Comment by mozillazg** [comment]
@onsunsl 你好，可以发 PR 到 https://github.com/mozillazg/phrase-pinyin-data 这个仓库。

格式转换可以使用 https://github.com/mozillazg/stpinyin 这个程序。如果你不方便转的话，可以把原始内容发 PR 到 https://github.com/mozillazg/phrase-pinyin-data，由我来转换。
