### ISSUE TITLE
pinyin函数能否支持separator=''

### ISSUE THREAD

**Issue by iloveyo123u1** [mozillazg/python-pinyin#68]
类似  slug(name, separator='')

谢谢

**Comment by mozillazg** [comment]
@iloveyo123u1 你想实现怎样的效果？建议写一个辅助函数来实现你的需求，而不是修改 `pinyin` 函数。

**Comment by iloveyo123u1** [comment]
默认输出是 ['ni', 'hao', 'ma'] ， 加了 separator=''，后 希望生成的是 nihaoma ,没有任何间隔，直接就是所有拼音，slug这个函数，就支持这个功能

,如下：


```
from pypinyin import pinyin, lazy_pinyin, slug
slug(‘你好吗’, separator='')
# 输出 nihaoma
```

希望pinyin 也支持slug的这个separator 参数

**Comment by mozillazg** [comment]
@iloveyo123u1 `slug` 就可以实现你的需求：

```python
>>> slug('你好吗', style=TONE, separator='')
'nǐhǎoma'
```

**Comment by iloveyo123u1** [comment]
但是我希望他头上没有 音调， 直接是 nihaoma, 而不是 'nǐhǎoma'

**Comment by mozillazg** [comment]
@iloveyo123u1 你上面的例子中 `slug` 默认就是没有声调呀：

```python
>>> slug('你好吗', separator='')
'nihaoma'
```

为什么一定要修改 `pinyin` 函数呢，`slug` 已经可以满足你的需求了。

**Comment by iloveyo123u1** [comment]
哦哦。看明白了， 谢谢
