### ISSUE TITLE
有支持拼音分词的功能吗？如输入nihaomadage,输出ni-hao-ma-da-ge

### ISSUE THREAD

**Issue by iloveyo123u1** [mozillazg/python-pinyin#70]
把输入的一长段拼音， 切分为单个字的拼音

如： jintiandetianqikezhendebuhaoya

切分为  jint,tian,de,tian.qi,ke,zhen,de,bu,hao,ya 这样的单个汉字的拼音

**Comment by mozillazg** [comment]
不支持这个功能。

**Comment by iloveyo123u1** [comment]
请问有这个计划吗？  或者你知道有什么东西能实现这个功能吗

**Comment by mozillazg** [comment]
@iloveyo123u1 不打算支持这个功能。
不了解是否由现成的第三方模块可以实现这个功能，你可以考虑用 https://github.com/mozillazg/python-pinyin/issues/63 中提到的 最大正向分词 方法自己实现一个简单的拼音分词功能。
