### ISSUE TITLE
TONE2 风格下使用 5 表示轻声？

### ISSUE THREAD

**Issue by mozillazg** [mozillazg/python-pinyin#83]
之前用 0 表示后来在 https://github.com/mozillazg/python-pinyin/issues/50 去掉了 0。
最近看了一下，好像一般倾向于使用 5 表示轻声？

还是维持现状，对于轻声不用任何数字标识？

**Comment by zuoxiang95** [comment]
@mozillazg 对，一般轻声是倾向于使用5来表示的

**Comment by agangzz** [comment]
使用 5 表示轻声比较常见，例如kaldi里面。如果要使用 5 表示轻声，pypinpin目前是否支持？如果不支持，怎么做一个快速的修改或实现？

**Comment by mozillazg** [comment]
@agangzz 目前不支持。需要支持的话，有一些 #50 中提到的问题需要解决（类似那个 `侵略 -> qi1n lv0e4` 的问题）

**Comment by YCY1998** [comment]
现在想把轻声标注成5，应该怎么做？

**Comment by mozillazg** [comment]
@YCY1998 可以按照 拼音声调标注规则 对结果做二次处理，找到应该把调标到哪个字母上，如果那个字母上没声调的话就是轻声。

**Comment by mozillazg** [comment]
@melspectrum007 不知道你指的是否是类似 https://github.com/mozillazg/python-pinyin/issues/52 这里的效果？

**Comment by mozillazg** [comment]
最新版增加了一个实现使用 5 标识轻声的辅助方法，详见文档：https://pypinyin.readthedocs.io/zh_CN/master/contrib.html#neutraltonewith5mixin

**Comment by v-yunbin** [comment]
如何使用0作为轻声？
