### ISSUE TITLE
分词建议用trie树实现最大正向匹配

### ISSUE THREAD

**Issue by xtco3o** [mozillazg/python-pinyin#90]
结巴分词有问题
比如
招商银行分词就是”招商银行“，然后拼音标注成为['zhao', 'shang', 'yin', 'xing']
但是单独对银行标注的时候，拼音是对的

事实上，根本就不应该用结巴分词，请参考
https://github.com/isnowfy/snownlp
这里的拼音标注，用trie树按多音词表实现最大正向匹配

另外我看拼音词表，其实保留最短的银行就好了，什么农业银行这种都可以去掉。

**Comment by mozillazg** [comment]
@xtco3o 感谢你的建议。

* 关于使用最大正向匹配的建议，欢迎提交 PR 或者在这个 PR https://github.com/mozillazg/python-pinyin/pull/81 的基础上进行修改。
* 关于精简词表的建议，这个是一个非常浩大的工程，欢迎帮忙一起改进。可以到这里提 PR: https://github.com/mozillazg/phrase-pinyin-data

**Comment by mozillazg** [comment]
今天发布的版本（v0.25.0）已经内置了一个最大匹配分词模块，使用方法:

```python
>>> from pypinyin import pinyin
>>> from pypinyin.contrib.mmseg import seg
>>> pinyin(seg.cut('招商银行'))       # 使用最大匹配分词
[['zhāo'], ['shāng'], ['yín'], ['háng']]
>>>
>>> pinyin('招商银行')                     # 使用 jieba 分词
Building prefix dict from the default dictionary ...
Loading model from cache /var/folders/s6/z9r_07h53pj_d4x7qjszwmbw0000gn/T/jieba.cache
Loading model cost 0.959 seconds.
Prefix dict has been built succesfully.
[['zhāo'], ['shāng'], ['yín'], ['xíng']]
>>>
```

**Comment by mozillazg** [comment]
下一步会改为默认使用这个最大匹配分词模块来分词，不再自动调用 jieba 进行分词。

**Comment by mozillazg** [comment]
最新发布的版本 0.26.0 已经改为默认使用这个最大匹配分词模块来分词了。

**Comment by zgdlime** [comment]
@xtco3o
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！
