### ISSUE TITLE
关于编码问题

### ISSUE THREAD

**Issue by onsunsl** [mozillazg/python-pinyin#92]
在代码总使用style = 0输出pinyin如下：

        textPY = pinyin(text, style=0)  # 全部拼音
        textSM = pinyin(text, style=3)  # 全部声母
        textYM = pinyin(text, style=5)  # 全部韵母
        logging.debug('{0}, {1}'.format(text, textPY))

win10 python3.5 输出两种不同结果。
 
pyinstaller 打包运行结果：
[line:389] - DEBUG: ['大', '家', '好'], [['dà'], ['jiā'], ['hǎo']]

源码运行结果：
[line:389] - DEBUG: ['大', '家', '好'], [['da'], ['jia'], ['hao']]

会不会是编码问题？

**Comment by onsunsl** [comment]
测试代码：

import pypinyin
text = '大家好'
print(text, pypinyin.pinyin(text, style = 0))

在pycharm里能正常输出：
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\onsun\AppData\Local\Temp\jieba.cache
Loading model cost 0.991 seconds.
大家好 [['da'], ['jia'], ['hao']]
Prefix dict has been built succesfully.

>pyinstaller test.py
75 INFO: PyInstaller: 3.3.dev0+c45dabfeb
75 INFO: Python: 3.5.3
76 INFO: Platform: Windows-10-10.0.14393-SP0
77 INFO: wrote D:\AnyCode\robot3DWorkplace\server\project\testPyPinyin.spec
79 INFO: UPX is not available.
98 INFO: Extending PYTHONPATH with paths
.............

>test.exe
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\onsun\AppData\Local\Temp\jieba.cache
Loading model cost 0.944 seconds.
Prefix dict has been built succesfully.
大家好 [['dà'], ['jiā'], ['hǎo']]

**Comment by mozillazg** [comment]
这个是因为用 pyinstaller 打包的问题。

**Comment by mozillazg** [comment]
@onsunsl 麻烦试一下 https://github.com/mozillazg/python-pinyin/pull/93 的改动是否解决了你的问题。

**Comment by onsunsl** [comment]
好了。按#93的改动方法解决了。
