### ISSUE TITLE
python2.7.5 不能正确安装

### ISSUE THREAD

**Issue by liuxiawei** [mozillazg/python-pinyin#98]
pip install pypinyin 
源码在编译时出错，上一句为
byte-compiling build/bdist.linux-x86_64/egg/pypinyin/phrases_dict.py to phrases_dict.pyc
此时未报错，直接显示为killed，下载源码也一样。求解

**Comment by mozillazg** [comment]
@liuxiawei 
你试试：

* 机器的内存是否不够
* 内存够的话，升级一下 pip 后再试试： `pip install -U pip`
* 安装时使用 `-v` 参数看看具体日志: `pip install pypinyin -v`

**Comment by mozillazg** [comment]
这个问题无法复现。

**Comment by aka863** [comment]
我在bandwagonhost的vps上也遇到了这个问题。
操作系统是 Debian 8.0 x86_64，内存256MB。
无论是使用系统自带的pip2，还是自己编译安装的python3.6，都会被killed。
网上搜了搜，有人说是内存不足造成的。

root@localhost:/var/log# pip install pypinyin
Collecting pypinyin
  Using cached pypinyin-0.27.0-py2.py3-none-any.whl
Requirement already satisfied: enum34; python_version < "3.4" in /usr/local/lib/python2.7/dist-packages (from pypinyin)
Installing collected packages: pypinyin
Killed

**Comment by mozillazg** [comment]
@aka863 是的，一般终端输出 `Killed` 都是内存超了的原因。你可以在执行 pip 命令前先看一下剩余内存(通过 `free` 命令查看）。

**Comment by xiaomiba0904** [comment]
我也出现同样的问题，内存在200M左右出现Killed，空出300以上就可以解决了

**Comment by zgdlime** [comment]
@liuxiawei
请问python-pinyin如何批量处理？

运行环境
操作系统：Windows10
Python 版本：python-3.4.3
pypinyin 版本：v0.33.0

我有一个文本文件b.txt，utf-8格式，文件里面有内容：
这个
进行
因为
还是
时候
看到
……
想把转换成汉语拼音，该如何操作？

能批处理、拖叠文件等一步到位吗？
指教一下吧！谢！
